import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getDefaultLanguage = (): Language => {
  const urlParams = new URLSearchParams(window.location.search);
  const urlLang = urlParams.get('lang') as Language;
  if (urlLang && ['fr', 'en'].includes(urlLang)) return urlLang;
  
  const saved = localStorage.getItem('signatech-language') as Language;
  if (saved && ['fr', 'en'].includes(saved)) return saved;
  
  const browserLang = navigator.language.toLowerCase();
  const country = Intl.DateTimeFormat().resolvedOptions().timeZone;
  
  if (browserLang.startsWith('fr') || country.includes('Casablanca') || country.includes('Africa')) {
    return 'fr';
  }
  
  return 'en';
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(getDefaultLanguage);

  useEffect(() => {
    localStorage.setItem('signatech-language', language);
    document.documentElement.lang = language;
    
    const url = new URL(window.location.href);
    url.searchParams.set('lang', language);
    window.history.replaceState({}, '', url.toString());
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',
    'nav.quote': 'Devis Gratuit',
    'hero.badge': '15+ années d\'expérience',
    'hero.title1': 'SOLUTIONS',
    'hero.title2': 'CRÉATIVES',
    'hero.subtitle': 'Nous transformons vos idées en',
    'hero.subtitle.highlight': 'solutions visuelles efficaces',
    'hero.subtitle.end': 'qui renforcent votre image',
    'hero.cta.primary': 'Créons ensemble',
    'hero.cta.secondary': 'Découvrir nos créations',
    'stats.experience': 'Années d\'expérience',
    'stats.projects': 'Projets réalisés',
    'stats.clients': 'Clients satisfaits',
    'stats.solutions': 'Solutions sur mesure',
    'services.badge': 'Nos Services',
    'services.title1': 'SOLUTIONS',
    'services.title2': 'PROFESSIONNELLES',
    'services.subtitle': 'Des services complets adaptés à vos besoins en communication visuelle et PLV',
    'services.design.title': 'Conception & Développement',
    'services.design.desc': 'Création sur mesure de vos supports de communication et PLV avec notre équipe de designers expérimentés.',
    'services.design.desc_detailed': 'Notre équipe de designers expérimentés transforme vos idées en créations visuelles exceptionnelles, du concept initial à la réalisation finale.',
    'services.design.feature1': 'Design personnalisé',
    'services.design.feature2': 'Prototypage',
    'services.design.feature3': 'Validation client',
    'services.retail.title': 'Produits PLV Retail',
    'services.retail.desc': 'Solutions complètes pour vos points de vente : présentoirs, displays, mobilier commercial.',
    'services.retail.desc_detailed': 'Solutions complètes pour optimiser vos points de vente avec des présentoirs, displays et mobilier commercial qui captent l\'attention et stimulent les ventes.',
    'services.retail.feature1': 'Présentoirs sur mesure',
    'services.retail.feature2': 'Mobilier retail',
    'services.retail.feature3': 'Displays interactifs',
    'services.seasonal.title': 'Fournitures Saisonnières',
    'services.seasonal.desc': 'Campagnes promotionnelles et supports temporaires pour vos événements spéciaux.',
    'services.seasonal.desc_detailed': 'Supports promotionnels temporaires et décorations saisonnières qui créent l\'événement et marquent les esprits lors de vos campagnes spéciales.',
    'services.seasonal.feature1': 'Campagnes événementielles',
    'services.seasonal.feature2': 'Supports temporaires',
    'services.seasonal.feature3': 'Décoration saisonnière',
    'services.signage.title': 'Habillage & Signalétique',
    'services.signage.desc': 'Transformation complète de vos façades et espaces avec notre expertise en signalétique.',
    'services.signage.desc_detailed': 'Métamorphose complète de vos façades et espaces avec notre expertise en signalétique, enseignes lumineuses et habillage architectural.',
    'services.signage.feature1': 'Habillage façades',
    'services.signage.feature2': 'Enseignes lumineuses',
    'services.signage.feature3': 'Signalétique directionnelle',
    'services.cta': 'Explorer nos talents',
    'portfolio.badge': 'Nos Réalisations',
    'portfolio.title1': 'PROJETS',
    'portfolio.title2': 'RÉALISÉS',
    'portfolio.subtitle': 'Découvrez nos projets qui allient créativité et efficacité commerciale',
    'portfolio.facade.title': 'Façade Révolutionnaire',
    'portfolio.facade.desc': 'Une transformation spectaculaire qui redéfinit l\'identité visuelle urbaine.',
    'portfolio.plv.title': 'PLV Révolutionnaire',
    'portfolio.plv.desc': 'Des expériences d\'achat immersives qui transforment chaque visite en aventure.',
    'portfolio.craft.title': 'Maîtrise Artisanale',
    'portfolio.craft.desc': 'L\'expertise technique au service de visions créatives audacieuses.',
    'portfolio.cta': 'Explorer toutes nos œuvres',
    'testimonials.badge': 'Témoignages Clients',
    'testimonials.title1': 'AVIS',
    'testimonials.title2': 'CLIENTS',
    'testimonials.subtitle': 'Découvrez les retours de nos clients sur nos réalisations',
    'testimonials.cocacola.role': 'Responsable Marketing',
    'testimonials.cocacola.content': 'Signa Tech a transformé nos points de vente avec des solutions PLV exceptionnelles. Leur créativité et professionnalisme sont remarquables.',
    'testimonials.juver.role': 'Directeur Commercial',
    'testimonials.juver.content': 'Un partenaire de confiance depuis plusieurs années. La qualité de leurs réalisations et le respect des délais sont exemplaires.',
    'testimonials.expleo.role': 'Chef de Projet',
    'testimonials.expleo.content': 'L\'expertise technique et l\'innovation de Signa Tech ont considérablement amélioré notre visibilité commerciale.',
    'cta.title1': 'RÉALISONS',
    'cta.title2': 'VOTRE PROJET',
    'cta.title3': 'ensemble',
    'cta.subtitle': 'Prêt à développer votre',
    'cta.subtitle.highlight': 'projet',
    'cta.subtitle.end': 'avec nous ?',
    'cta.primary': 'Créons le futur',
    'cta.secondary': 'Parlons maintenant',
    'company.name': 'Signa Tech',
    'company.tagline': 'Solutions PLV & Signalétique',
    'company.address': 'Zone Industrielle Gzenaya lot 376, Tanger, Morocco',
    'footer.description': 'Depuis plus de 15 ans, nous créons des solutions de communication créatives et innovantes pour renforcer la visibilité de votre marque.',
    'footer.navigation': 'Navigation',
    'footer.services': 'Nos Services',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.legal': 'Mentions Légales',
    'about.hero.badge': 'Notre Histoire',
    'about.hero.title1': 'EXPERTS EN',
    'about.hero.title2': 'COMMUNICATION',
    'about.hero.subtitle': '15+ années d\'expérience en solutions visuelles et PLV',
    'about.story.badge': 'Notre Épopée',
    'about.story.title': 'Notre Histoire Depuis Plus de 15 Ans',
    'about.story.p1': 'Fondée à Tanger, Signa Tech s\'est spécialisée dans les solutions de communication visuelle et PLV. Nous accompagnons nos clients dans le développement de leur image de marque.',
    'about.story.p2': 'Nos réalisations sont conçues pour répondre efficacement à vos objectifs commerciaux tout en respectant votre identité visuelle.',
    'about.story.p3': 'Avec plus de 500 projets réalisés et la confiance de clients prestigieux comme Coca-Cola, Juver et Expleo Group, nous continuons d\'innover pour repousser les frontières du possible.',
    'about.values.badge': 'Nos Valeurs Fondamentales',
    'about.values.title1': 'CE QUI NOUS',
    'about.values.title2': 'DÉFINIT',
    'about.values.quality.title': 'Excellence Qualité',
    'about.values.quality.desc': 'Nous nous engageons à livrer des créations d\'une qualité irréprochable, dépassant systématiquement les attentes de nos clients.',
    'about.values.confidentiality.title': 'Confidentialité Absolue',
    'about.values.confidentiality.desc': 'Vos projets et idées sont protégés avec le plus grand soin. La discrétion est au cœur de notre relation client.',
    'about.values.innovation.title': 'Innovation Audacieuse',
    'about.values.innovation.desc': 'Nous repoussons constamment les limites créatives pour concevoir des solutions qui marquent et transforment.',
    'about.mission.title': 'Notre Mission',
    'about.mission.desc': 'Transformer chaque projet en une expérience visuelle exceptionnelle qui dépasse les attentes, en alliant créativité audacieuse, innovation technique et excellence artisanale pour donner vie aux visions les plus ambitieuses de nos clients.',
    'about.vision.title': 'Notre Vision',
    'about.vision.desc': 'Devenir la référence incontournable en communication visuelle au Maroc et en Afrique, reconnue pour notre capacité à révolutionner l\'art de la signalétique et à créer des œuvres qui marquent durablement les esprits.',
    'about.cta.title1': 'CRÉONS ENSEMBLE',
    'about.cta.title2': 'VOTRE LÉGENDE',
    'about.cta.subtitle': 'Rejoignez l\'aventure créative et découvrez ce que nous pouvons accomplir ensemble',
    'about.cta.button': 'Démarrons votre projet',
    'contact.hero.badge': 'Parlons Création',
    'contact.hero.title1': 'CONNECTONS',
    'contact.hero.title2': 'NOS ÉNERGIES',
    'contact.hero.subtitle': 'Prêt à transformer vos idées en réalité visuelle ? Contactez-nous !',
    'contact.form.title': 'Démarrons Votre Projet',
    'contact.form.subtitle': 'Partagez-nous votre vision et nous la transformerons en chef-d\'œuvre visuel.',
    'contact.form.name': 'Nom complet',
    'contact.form.company': 'Entreprise',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Téléphone',
    'contact.form.project': 'Type de projet',
    'contact.form.message': 'Décrivez votre vision',
    'contact.form.submit': 'Envoyer ma demande',
    'contact.phone.title': 'Téléphone',
    'contact.phone.desc': 'Appelez-nous directement',
    'contact.email.title': 'Email',
    'contact.email.desc': 'Écrivez-nous',
    'contact.address.title': 'Adresse',
    'contact.address.desc': 'Visitez notre atelier',
    'contact.hours.title': 'Horaires',
    'contact.hours.desc': 'Nos heures d\'ouverture',
    'contact.whatsapp': 'Chatter sur WhatsApp',
    'contact.map.title': 'Trouvez-nous',
    'contact.form.name.label': 'Nom complet',
    'contact.form.name.placeholder': 'Votre nom',
    'contact.form.company.label': 'Entreprise',
    'contact.form.company.placeholder': 'Nom de votre entreprise',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'votre@email.com',
    'contact.form.phone.label': 'Téléphone',
    'contact.form.phone.placeholder': '+212 X XX XX XX XX',
    'contact.form.project.label': 'Type de projet',
    'contact.form.project.placeholder': 'Sélectionnez votre besoin',
    'contact.form.project.option1': 'Conception & Développement',
    'contact.form.project.option2': 'Produits PLV Retail',
    'contact.form.project.option3': 'Fournitures Saisonnières',
    'contact.form.project.option4': 'Habillage & Signalétique',
    'contact.form.project.option5': 'Autre projet créatif',
    'contact.form.message.label': 'Décrivez votre vision',
    'contact.form.message.placeholder': 'Partagez-nous votre idée, vos objectifs, votre budget approximatif...',
    'contact.form.submit.text': 'Envoyer ma demande',
    'contact.form.send': 'Envoyer ma demande',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.toggle': 'Ajouter des spécifications détaillées à ma demande',
    'contact.form.service.type': 'Type de service',
    'contact.form.service.printing': 'Impression',
    'contact.form.service.cutting': 'Découpe Plotter',
    'contact.form.service.cnc': 'CNC',
    'contact.form.service.laser': 'Laser',
    'contact.form.material': 'Matériau',
    'contact.form.size': 'Dimensions (L × H)',
    'contact.form.quantity': 'Quantité',
    'contact.form.indoor_outdoor': 'Usage',
    'contact.form.indoor': 'Intérieur',
    'contact.form.outdoor': 'Extérieur',
    'contact.form.finishing': 'Finition',
    'contact.form.artwork_ready': 'Visuel prêt à imprimer ?',
    'contact.form.yes': 'Oui',
    'contact.form.no': 'Non',
    'contact.form.thickness': 'Épaisseur',
    'contact.form.colors': 'Couleur(s) du vinyle',
    'contact.form.cutting_application': 'Service',
    'contact.form.cutting_only': 'Découpe uniquement',
    'contact.form.cutting_application_both': 'Découpe + Pose',
    'contact.form.design_ready': 'Fichier de conception prêt ?',
    'contact.form.cnc_finishing': 'Finition CNC',
    'contact.form.job_type': 'Type de travail',
    'contact.form.cutting': 'Découpe',
    'contact.form.engraving': 'Gravure',
    'contact.form.both': 'Les deux',
    'contact.form.detail_level': 'Niveau de détail',
    'contact.form.high_resolution': 'Haute résolution',
    'contact.form.standard': 'Standard',
    'contact.info.title': 'Informations de Contact',
    'contact.info.subtitle': 'Plusieurs moyens de nous joindre pour concrétiser vos projets',
    'contact.info.phone.title': 'Téléphone',
    'contact.info.phone.value': '+212 5 39 40 31 33',
    'contact.info.email.title': 'Email',
    'contact.info.email.value': 'contact@signatech.ma',
    'contact.info.address.title': 'Adresse',
    'contact.info.address.value': 'Zone Industrielle Gzenaya, Lot 376, Tanger, Maroc',
    'contact.info.hours.title': 'Horaires',
    'contact.info.hours.value': 'Lun-Ven: 8h-18h | Sam: 8h-13h',
    'contact.hours.mon_fri': 'Lun - Ven: 8h00 - 18h00',
    'contact.hours.saturday': 'Samedi: 8h00 - 13h00',
    'contact.hours.sunday': 'Dimanche: Fermé',
    'contact.map.placeholder': 'Carte Google Maps à intégrer',
    'services.hero.badge': 'Nos Super-pouvoirs',
    'services.hero.title1': 'SERVICES',
    'services.hero.title2': 'EXTRAORDINAIRES',
    'services.hero.subtitle': 'Chaque service est une nouvelle aventure créative où nous repoussons les limites du possible',
    'services.design.subtitle': 'Créativité sur mesure',
    'services.design.highlight': '15+ années d\'expertise créative',
    'services.retail.subtitle': 'Expériences d\'achat immersives',
    'services.retail.highlight': '500+ projets retail réalisés',
    'services.seasonal.subtitle': 'Campagnes événementielles',
    'services.seasonal.highlight': 'Réactivité 24h/48h',
    'services.signage.subtitle': 'Transformation d\'espaces',
    'services.signage.highlight': 'Garantie 5 ans sur nos installations',
    'services.process.badge': 'Notre Processus Créatif',
    'services.process.title1': 'DE L\'IDÉE À LA',
    'services.process.title2': 'RÉALISATION',
    'services.process.step1.title': 'Écoute & Analyse',
    'services.process.step1.desc': 'Compréhension approfondie de vos besoins et objectifs',
    'services.process.step2.title': 'Conception Créative',
    'services.process.step2.desc': 'Développement de concepts innovants et sur mesure',
    'services.process.step3.title': 'Validation & Prototype',
    'services.process.step3.desc': 'Tests et ajustements pour garantir la perfection',
    'services.process.step4.title': 'Réalisation & Livraison',
    'services.process.step4.desc': 'Production et installation avec suivi qualité',
    'services.cta.title1': 'CRÉONS VOTRE',
    'services.cta.title2': 'CHEF-D\'ŒUVRE',
    'services.cta.subtitle': 'Quel que soit votre défi créatif, nous avons la solution pour le transformer en succès',
    'services.cta.button': 'Discutons de votre projet',
    // Admin translations
    'admin.notifications.enabled': 'Activées',
    'admin.notifications.disabled': 'Désactivées',
    'admin.notifications.enable': 'Activer',
    'admin.notifications.disable': 'Désactiver',
    'admin.notifications.email': 'Notifications par email',
    'admin.total_users': 'Total Users',
    'admin.total_submissions': 'Total Submissions',
    'admin.admin_users': 'Admin Users',
    'admin.total_admins': 'Total admins',
    'admin.all_statuses': 'Tous les statuts',
    'admin.pending': 'En attente',
    'admin.completed': 'Terminé',
    'admin.reviews': 'Avis',
    'admin.contact_settings': 'Paramètres de Contact',
    'admin.registered_users': 'Registered Users',
    // Rating translations
    'rating.manage_reviews': 'Gestion des Avis',
    'rating.approved': 'Approuvé',
    'rating.pending': 'En attente',
    'rating.featured': 'Mis en avant',
    'rating.hide': 'Masquer',
    'rating.approve': 'Approuver',
    'rating.remove': 'Retirer',
    'rating.feature': 'Mettre en avant',
    'rating.no_reviews': 'Aucun avis pour le moment',
    'rating.status_updated': 'Statut mis à jour',
    'rating.status_updated_desc': 'Le statut de l\'avis a été modifié',
    'rating.delete_confirm': 'Êtes-vous sûr de vouloir supprimer cet avis ?',
    'rating.deleted': 'Avis supprimé',
    'rating.deleted_desc': 'L\'avis a été supprimé avec succès',
    'rating.delete_error': 'Impossible de supprimer l\'avis',
    'rating.update_error': 'Impossible de mettre à jour le statut',
    'rating.customer_review': 'Avis client',
    'rating.thank_you': 'Merci pour votre avis!',
    'rating.already_rated': 'Vous avez déjà donné votre avis. Un seul avis par client est autorisé.',
    'rating.not_eligible': 'Pas encore éligible',
    'rating.eligibility_desc': 'Vous pourrez donner votre avis une fois qu\'une de vos demandes sera terminée.',
    'rating.give_review': 'Donnez votre avis',
    'rating.send_review': 'Envoyer mon avis',
    'rating.send_error': 'Impossible d\'envoyer votre avis',
    'rating.view_all': 'Voir tous les avis',
    'rating.reviews': 'avis',
    'rating.customer_reviews': 'Avis Clients',
    'rating.all_reviews': 'Tous les avis'
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.quote': 'Free Quote',
    'hero.badge': '15+ years of experience',
    'hero.title1': 'CREATIVE',
    'hero.title2': 'SOLUTIONS',
    'hero.subtitle': 'We transform your ideas into',
    'hero.subtitle.highlight': 'effective visual solutions',
    'hero.subtitle.end': 'that strengthen your brand',
    'hero.cta.primary': 'Create Together',
    'hero.cta.secondary': 'Discover Our Creations',
    'stats.experience': 'Years of Experience',
    'stats.projects': 'Projects Completed',
    'stats.clients': 'Satisfied Clients',
    'stats.solutions': 'Custom Solutions',
    'services.badge': 'Our Services',
    'services.title1': 'PROFESSIONAL',
    'services.title2': 'SOLUTIONS',
    'services.subtitle': 'Comprehensive services tailored to your visual communication and POS needs',
    'services.design.title': 'Design & Development',
    'services.design.desc': 'Custom creation of your communication materials and POS displays with our experienced design team.',
    'services.design.desc_detailed': 'Our experienced design team transforms your ideas into exceptional visual creations, from initial concept to final realization.',
    'services.design.feature1': 'Custom Design',
    'services.design.feature2': 'Prototyping',
    'services.design.feature3': 'Client Validation',
    'services.retail.title': 'Retail POS Products',
    'services.retail.desc': 'Complete solutions for your points of sale: displays, stands, commercial furniture.',
    'services.retail.desc_detailed': 'Complete solutions to optimize your points of sale with displays, stands and commercial furniture that capture attention and stimulate sales.',
    'services.retail.feature1': 'Custom Displays',
    'services.retail.feature2': 'Retail Furniture',
    'services.retail.feature3': 'Interactive Displays',
    'services.seasonal.title': 'Seasonal Supplies',
    'services.seasonal.desc': 'Promotional campaigns and temporary supports for your special events.',
    'services.seasonal.desc_detailed': 'Temporary promotional supports and seasonal decorations that create events and leave lasting impressions during your special campaigns.',
    'services.seasonal.feature1': 'Event Campaigns',
    'services.seasonal.feature2': 'Temporary Supports',
    'services.seasonal.feature3': 'Seasonal Decoration',
    'services.signage.title': 'Cladding & Signage',
    'services.signage.desc': 'Complete transformation of your facades and spaces with our signage expertise.',
    'services.signage.desc_detailed': 'Complete metamorphosis of your facades and spaces with our expertise in signage, illuminated signs and architectural cladding.',
    'services.signage.feature1': 'Facade Cladding',
    'services.signage.feature2': 'Illuminated Signs',
    'services.signage.feature3': 'Directional Signage',
    'services.cta': 'Explore Our Talents',
    'portfolio.badge': 'Our Work',
    'portfolio.title1': 'COMPLETED',
    'portfolio.title2': 'PROJECTS',
    'portfolio.subtitle': 'Discover our projects that combine creativity with commercial effectiveness',
    'portfolio.facade.title': 'Revolutionary Facade',
    'portfolio.facade.desc': 'A spectacular transformation that redefines urban visual identity.',
    'portfolio.plv.title': 'Revolutionary POS',
    'portfolio.plv.desc': 'Immersive shopping experiences that transform every visit into an adventure.',
    'portfolio.craft.title': 'Artisanal Mastery',
    'portfolio.craft.desc': 'Technical expertise serving bold creative visions.',
    'portfolio.cta': 'Explore All Our Works',
    'testimonials.badge': 'Client Testimonials',
    'testimonials.title1': 'CLIENT',
    'testimonials.title2': 'FEEDBACK',
    'testimonials.subtitle': 'See what our clients say about our work',
    'testimonials.cocacola.role': 'Marketing Manager',
    'testimonials.cocacola.content': 'Signa Tech transformed our points of sale with exceptional POS solutions. Their creativity and professionalism are remarkable.',
    'testimonials.juver.role': 'Commercial Director',
    'testimonials.juver.content': 'A trusted partner for several years. The quality of their work and respect for deadlines are exemplary.',
    'testimonials.expleo.role': 'Project Manager',
    'testimonials.expleo.content': 'Signa Tech\'s technical expertise and innovation have significantly improved our commercial visibility.',
    'cta.title1': 'START YOUR',
    'cta.title2': 'PROJECT',
    'cta.title3': 'with us',
    'cta.subtitle': 'Ready to develop your',
    'cta.subtitle.highlight': 'project',
    'cta.subtitle.end': 'together?',
    'cta.primary': 'Create the Future',
    'cta.secondary': 'Talk Now',
    'company.name': 'Signa Tech',
    'company.tagline': 'POS & Signage Solutions',
    'company.address': 'Industrial Zone Gzenaya lot 376, Tangier, Morocco',
    'footer.description': 'For over 15 years, we have been creating creative and innovative communication solutions to strengthen your brand visibility.',
    'footer.navigation': 'Navigation',
    'footer.services': 'Our Services',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'about.hero.badge': 'Our Story',
    'about.hero.title1': 'COMMUNICATION',
    'about.hero.title2': 'EXPERTS',
    'about.hero.subtitle': '15+ years of experience in visual solutions and POS displays',
    'about.story.badge': 'Our Journey',
    'about.story.title': 'Our Story Over 15 Years',
    'about.story.p1': 'Founded in Tangier, Signa Tech specializes in visual communication solutions and POS displays. We support our clients in developing their brand image.',
    'about.story.p2': 'Our work is designed to effectively meet your commercial objectives while respecting your visual identity.',
    'about.story.p3': 'With over 500 completed projects and the trust of prestigious clients like Coca-Cola, Juver and Expleo Group, we continue to innovate to push the boundaries of possibility.',
    'about.values.badge': 'Our Core Values',
    'about.values.title1': 'WHAT',
    'about.values.title2': 'DEFINES US',
    'about.values.quality.title': 'Quality Excellence',
    'about.values.quality.desc': 'We are committed to delivering creations of impeccable quality, consistently exceeding our clients\' expectations.',
    'about.values.confidentiality.title': 'Absolute Confidentiality',
    'about.values.confidentiality.desc': 'Your projects and ideas are protected with the utmost care. Discretion is at the heart of our client relationship.',
    'about.values.innovation.title': 'Bold Innovation',
    'about.values.innovation.desc': 'We constantly push creative boundaries to design solutions that make an impact and transform.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Transform every project into an exceptional visual experience that exceeds expectations, combining bold creativity, technical innovation and artisanal excellence to bring our clients\' most ambitious visions to life.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'Become the undisputed reference in visual communication in Morocco and Africa, recognized for our ability to revolutionize the art of signage and create works that leave lasting impressions.',
    'about.cta.title1': 'CREATE TOGETHER',
    'about.cta.title2': 'YOUR LEGEND',
    'about.cta.subtitle': 'Join the creative adventure and discover what we can accomplish together',
    'about.cta.button': 'Start Your Project',
    'contact.hero.badge': 'Let\'s Talk Creation',
    'contact.hero.title1': 'CONNECT OUR',
    'contact.hero.title2': 'ENERGIES',
    'contact.hero.subtitle': 'Ready to transform your ideas into visual reality? Contact us!',
    'contact.form.title': 'Start Your Project',
    'contact.form.subtitle': 'Share your vision with us and we\'ll transform it into a visual masterpiece.',
    'contact.form.name': 'Full Name',
    'contact.form.company': 'Company',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.project': 'Project Type',
    'contact.form.message': 'Describe Your Vision',
    'contact.form.submit': 'Send My Request',
    'contact.phone.title': 'Phone',
    'contact.phone.desc': 'Call us directly',
    'contact.email.title': 'Email',
    'contact.email.desc': 'Write to us',
    'contact.address.title': 'Address',
    'contact.address.desc': 'Visit our workshop',
    'contact.hours.title': 'Hours',
    'contact.hours.desc': 'Our opening hours',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.map.title': 'Find Us',
    'contact.form.name.label': 'Full Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.company.label': 'Company',
    'contact.form.company.placeholder': 'Your company name',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone.label': 'Phone',
    'contact.form.phone.placeholder': '+212 X XX XX XX XX',
    'contact.form.project.label': 'Project Type',
    'contact.form.project.placeholder': 'Select your need',
    'contact.form.project.option1': 'Design & Development',
    'contact.form.project.option2': 'Retail POS Products',
    'contact.form.project.option3': 'Seasonal Supplies',
    'contact.form.project.option4': 'Cladding & Signage',
    'contact.form.project.option5': 'Other creative project',
    'contact.form.message.label': 'Describe Your Vision',
    'contact.form.message.placeholder': 'Share your idea, objectives, approximate budget...',
    'contact.form.submit.text': 'Send My Request',
    'contact.form.send': 'Send My Request',
    'contact.form.sending': 'Sending...',
    'contact.form.toggle': 'Add detailed specifications to my request',
    'contact.form.service.type': 'Service Type',
    'contact.form.service.printing': 'Printing',
    'contact.form.service.cutting': 'Cutting Plotter',
    'contact.form.service.cnc': 'CNC',
    'contact.form.service.laser': 'Laser',
    'contact.form.material': 'Material',
    'contact.form.size': 'Size (W × H)',
    'contact.form.quantity': 'Quantity',
    'contact.form.indoor_outdoor': 'Usage',
    'contact.form.indoor': 'Indoor',
    'contact.form.outdoor': 'Outdoor',
    'contact.form.finishing': 'Finishing',
    'contact.form.artwork_ready': 'Ready-to-print artwork?',
    'contact.form.yes': 'Yes',
    'contact.form.no': 'No',
    'contact.form.thickness': 'Thickness',
    'contact.form.colors': 'Vinyl Color(s)',
    'contact.form.cutting_application': 'Service',
    'contact.form.cutting_only': 'Cutting only',
    'contact.form.cutting_application_both': 'Cutting + Application',
    'contact.form.design_ready': 'Design file ready?',
    'contact.form.cnc_finishing': 'CNC Finishing',
    'contact.form.job_type': 'Job Type',
    'contact.form.cutting': 'Cutting',
    'contact.form.engraving': 'Engraving',
    'contact.form.both': 'Both',
    'contact.form.detail_level': 'Detail Level',
    'contact.form.high_resolution': 'High Resolution',
    'contact.form.standard': 'Standard',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Multiple ways to reach us to bring your projects to life',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.value': '+212 5 39 40 31 33',
    'contact.info.email.title': 'Email',
    'contact.info.email.value': 'contact@signatech.ma',
    'contact.info.address.title': 'Address',
    'contact.info.address.value': 'Industrial Zone Gzenaya, Lot 376, Tangier, Morocco',
    'contact.info.hours.title': 'Hours',
    'contact.info.hours.value': 'Mon-Fri: 8am-6pm | Sat: 8am-1pm',
    'contact.hours.mon_fri': 'Mon - Fri: 8:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday: 8:00 AM - 1:00 PM',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.map.placeholder': 'Google Maps to be integrated',
    'services.hero.badge': 'Our Superpowers',
    'services.hero.title1': 'EXTRAORDINARY',
    'services.hero.title2': 'SERVICES',
    'services.hero.subtitle': 'Every service is a new creative adventure where we push the boundaries of possibility',
    'services.design.subtitle': 'Custom Creativity',
    'services.design.highlight': '15+ years of creative expertise',
    'services.retail.subtitle': 'Immersive Shopping Experiences',
    'services.retail.highlight': '500+ retail projects completed',
    'services.seasonal.subtitle': 'Event Campaigns',
    'services.seasonal.highlight': '24h/48h responsiveness',
    'services.signage.subtitle': 'Space Transformation',
    'services.signage.highlight': '5-year warranty on our installations',
    'services.process.badge': 'Our Creative Process',
    'services.process.title1': 'FROM IDEA TO',
    'services.process.title2': 'REALIZATION',
    'services.process.step1.title': 'Listen & Analyze',
    'services.process.step1.desc': 'Deep understanding of your needs and objectives',
    'services.process.step2.title': 'Creative Design',
    'services.process.step2.desc': 'Development of innovative and custom concepts',
    'services.process.step3.title': 'Validation & Prototype',
    'services.process.step3.desc': 'Testing and adjustments to guarantee perfection',
    'services.process.step4.title': 'Production & Delivery',
    'services.process.step4.desc': 'Production and installation with quality monitoring',
    'services.cta.title1': 'CREATE YOUR',
    'services.cta.title2': 'MASTERPIECE',
    'services.cta.subtitle': 'Whatever your creative challenge, we have the solution to transform it into success',
    'services.cta.button': 'Let\'s discuss your project',
    // Admin translations
    'admin.notifications.enabled': 'Enabled',
    'admin.notifications.disabled': 'Disabled',
    'admin.notifications.enable': 'Enable',
    'admin.notifications.disable': 'Disable',
    'admin.notifications.email': 'Email notifications',
    'admin.total_users': 'Total Users',
    'admin.total_submissions': 'Total Submissions',
    'admin.admin_users': 'Admin Users',
    'admin.total_admins': 'Total admins',
    'admin.all_statuses': 'All statuses',
    'admin.pending': 'Pending',
    'admin.completed': 'Completed',
    'admin.reviews': 'Reviews',
    'admin.contact_settings': 'Contact Settings',
    'admin.registered_users': 'Registered Users',
    // Rating translations
    'rating.manage_reviews': 'Manage Reviews',
    'rating.approved': 'Approved',
    'rating.pending': 'Pending',
    'rating.featured': 'Featured',
    'rating.hide': 'Hide',
    'rating.approve': 'Approve',
    'rating.remove': 'Remove',
    'rating.feature': 'Feature',
    'rating.no_reviews': 'No reviews yet',
    'rating.status_updated': 'Status updated',
    'rating.status_updated_desc': 'Review status has been updated',
    'rating.delete_confirm': 'Are you sure you want to delete this review?',
    'rating.deleted': 'Review deleted',
    'rating.deleted_desc': 'Review has been deleted successfully',
    'rating.delete_error': 'Unable to delete review',
    'rating.update_error': 'Unable to update status',
    'rating.customer_review': 'Customer Review',
    'rating.thank_you': 'Thank you for your review!',
    'rating.already_rated': 'You have already given your review. Only one review per customer is allowed.',
    'rating.not_eligible': 'Not yet eligible',
    'rating.eligibility_desc': 'You will be able to give your review once one of your requests is completed.',
    'rating.give_review': 'Give your review',
    'rating.send_review': 'Send my review',
    'rating.send_error': 'Unable to send your review',
    'rating.view_all': 'View all reviews',
    'rating.reviews': 'reviews',
    'rating.customer_reviews': 'Customer Reviews',
    'rating.all_reviews': 'All reviews'
  }
};