import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getDefaultLanguage = (): Language => {
  const urlParams = new URLSearchParams(window.location.search);
  const urlLang = urlParams.get('lang') as Language;
  if (urlLang && ['fr', 'en'].includes(urlLang)) return urlLang;
  
  const saved = localStorage.getItem('signatech-language') as Language;
  if (saved && ['fr', 'en'].includes(saved)) return saved;
  
  const browserLang = navigator.language.toLowerCase();
  const country = Intl.DateTimeFormat().resolvedOptions().timeZone;
  
  if (browserLang.startsWith('fr') || country.includes('Casablanca') || country.includes('Africa')) {
    return 'fr';
  }
  
  return 'en';
};

  const currentYear = new Date().getFullYear();
  export const yearsOfExperience = (currentYear - 2008).toString()+"+";


export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(getDefaultLanguage);

  useEffect(() => {
    localStorage.setItem('signatech-language', language);
    document.documentElement.lang = language;
    
    const url = new URL(window.location.href);
    url.searchParams.set('lang', language);
    window.history.replaceState({}, '', url.toString());
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.fr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',
    'nav.quote': 'Devis Gratuit',
    'hero.badge': `${yearsOfExperience} années d\'expérience`,
    'hero.title1': 'SOLUTIONS',
    'hero.title2': 'CRÉATIVES',
    'hero.subtitle': 'Nous transformons vos idées en',
    'hero.subtitle.highlight': 'solutions visuelles efficaces',
    'hero.subtitle.end': 'qui renforcent votre image',
    'hero.cta.primary': 'Créons ensemble',
    'hero.cta.secondary': 'Découvrir nos créations',
    'stats.experience': 'Années d\'expérience',
    'stats.projects': 'Projets réalisés',
    'stats.clients': 'Clients satisfaits',
    'stats.solutions': 'Solutions sur mesure',
    'services.badge': 'Nos Services',
    'services.title1': 'SOLUTIONS',
    'services.title2': 'PROFESSIONNELLES',
    'services.subtitle': 'Des services complets adaptés à vos besoins en communication visuelle et PLV',
    'services.design.title': 'Conception & Développement',
    'services.design.desc': 'Création sur mesure de vos supports de communication et PLV avec notre équipe de designers expérimentés.',
    'services.design.desc_detailed': 'Notre équipe de designers expérimentés transforme vos idées en créations visuelles exceptionnelles, du concept initial à la réalisation finale.',
    'services.design.feature1': 'Design personnalisé',
    'services.design.feature2': 'Prototypage',
    'services.design.feature3': 'Validation client',
    'services.design.feature4': 'Consultation stratégique',
    'services.design.feature5': 'Recherche et tendances',
    'services.retail.title': 'Produits PLV Retail',
    'services.retail.desc': 'Solutions complètes pour vos points de vente : présentoirs, displays, mobilier commercial.',
    'services.retail.desc_detailed': 'Solutions complètes pour optimiser vos points de vente avec des présentoirs, displays et mobilier commercial qui captent l\'attention et stimulent les ventes.',
    'services.retail.feature1': 'Présentoirs sur mesure',
    'services.retail.feature2': 'Mobilier retail',
    'services.retail.feature3': 'Displays interactifs',
    'services.retail.feature4': 'Solutions modulaires',
    'services.retail.feature5': 'Aménagement d\'espaces',
    'services.seasonal.title': 'Fournitures Saisonnières',
    'services.seasonal.desc': 'Campagnes promotionnelles et supports temporaires pour vos événements spéciaux.',
    'services.seasonal.desc_detailed': 'Supports promotionnels temporaires et décorations saisonnières qui créent l\'événement et marquent les esprits lors de vos campagnes spéciales.',
    'services.seasonal.feature1': 'Campagnes événementielles',
    'services.seasonal.feature2': 'Supports temporaires',
    'services.seasonal.feature3': 'Décoration saisonnière',
    'services.seasonal.feature4': 'Événements spéciaux',
    'services.seasonal.feature5': 'Installation express',
    'services.signage.title': 'Habillage & Signalétique',
    'services.signage.desc': 'Transformation complète de vos façades et espaces avec notre expertise en signalétique.',
    'services.signage.desc_detailed': 'Métamorphose complète de vos façades et espaces avec notre expertise en signalétique, enseignes lumineuses et habillage architectural.',
    'services.signage.feature1': 'Habillage façades',
    'services.signage.feature2': 'Enseignes lumineuses',
    'services.signage.feature3': 'Signalétique directionnelle',
    'services.signage.feature4': 'Totems et pylônes',
    'services.signage.feature5': 'Marquage au sol',
    'services.cta': 'Explorer nos talents',
    'portfolio.badge': 'Nos Réalisations',
    'portfolio.title1': 'PROJETS',
    'portfolio.title2': 'RÉALISÉS',
    'portfolio.subtitle': 'Découvrez nos projets qui allient créativité et efficacité commerciale',
    'portfolio.facade.title': 'Façade Révolutionnaire',
    'portfolio.facade.desc': 'Une transformation spectaculaire qui redéfinit l\'identité visuelle urbaine.',
    'portfolio.plv.title': 'PLV Révolutionnaire',
    'portfolio.plv.desc': 'Des expériences d\'achat immersives qui transforment chaque visite en aventure.',
    'portfolio.craft.title': 'Maîtrise Artisanale',
    'portfolio.craft.desc': 'L\'expertise technique au service de visions créatives audacieuses.',
    'portfolio.cta': 'Explorer toutes nos œuvres',
    'testimonials.badge': 'Témoignages Clients',
    'testimonials.title1': 'AVIS',
    'testimonials.title2': 'CLIENTS',
    'testimonials.subtitle': 'Découvrez les retours de nos clients sur nos réalisations',
    'testimonials.cocacola.role': 'Responsable Marketing',
    'testimonials.cocacola.content': 'Signa Tech a transformé nos points de vente avec des solutions PLV exceptionnelles. Leur créativité et professionnalisme sont remarquables.',
    'testimonials.juver.role': 'Directeur Commercial',
    'testimonials.juver.content': 'Un partenaire de confiance depuis plusieurs années. La qualité de leurs réalisations et le respect des délais sont exemplaires.',
    'testimonials.expleo.role': 'Chef de Projet',
    'testimonials.expleo.content': 'L\'expertise technique et l\'innovation de Signa Tech ont considérablement amélioré notre visibilité commerciale.',
    'cta.title1': 'RÉALISONS',
    'cta.title2': 'VOTRE PROJET',
    'cta.title3': 'ensemble',
    'cta.subtitle': 'Prêt à développer votre',
    'cta.subtitle.highlight': 'projet',
    'cta.subtitle.end': 'avec nous ?',
    'cta.primary': 'Créons le futur',
    'cta.secondary': 'Parlons maintenant',
    'company.name': 'Signa Tech',
    'company.tagline': 'Solutions PLV & Signalétique',
    'company.address': 'Zone Industrielle Gzenaya lot 376, Tanger, Morocco',
    'footer.description': `Depuis plus de ${yearsOfExperience} ans, nous créons des solutions de communication créatives et innovantes pour renforcer la visibilité de votre marque.`,
    'footer.navigation': 'Navigation',
    'footer.services': 'Nos Services',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.legal': 'Mentions Légales',
    'about.hero.badge': 'Notre Histoire',
    'about.hero.title1': 'EXPERTS EN',
    'about.hero.title2': 'COMMUNICATION',
    'about.hero.subtitle': `${yearsOfExperience} années d\'expérience en solutions visuelles et PLV`,
    'about.story.badge': 'Notre Épopée',
    'about.story.title': `Notre Histoire Depuis Plus de ${yearsOfExperience} Ans`,
    'about.story.p1': 'Fondée à Tanger, Signa Tech s\'est spécialisée dans les solutions de communication visuelle et PLV. Nous accompagnons nos clients dans le développement de leur image de marque.',
    'about.story.p2': 'Nos réalisations sont conçues pour répondre efficacement à vos objectifs commerciaux tout en respectant votre identité visuelle.',
    'about.story.p3': 'Avec plus de 500 projets réalisés et la confiance de clients prestigieux comme Coca-Cola, Juver et Expleo Group, nous continuons d\'innover pour repousser les frontières du possible.',
    'about.values.badge': 'Nos Valeurs Fondamentales',
    'about.values.title1': 'CE QUI NOUS',
    'about.values.title2': 'DÉFINIT',
    'about.values.quality.title': 'Excellence Qualité',
    'about.values.quality.desc': 'Nous nous engageons à livrer des créations d\'une qualité irréprochable, dépassant systématiquement les attentes de nos clients.',
    'about.values.confidentiality.title': 'Confidentialité Absolue',
    'about.values.confidentiality.desc': 'Vos projets et idées sont protégés avec le plus grand soin. La discrétion est au cœur de notre relation client.',
    'about.values.innovation.title': 'Innovation Audacieuse',
    'about.values.innovation.desc': 'Nous repoussons constamment les limites créatives pour concevoir des solutions qui marquent et transforment.',
    'about.mission.title': 'Notre Mission',
    'about.mission.desc': 'Transformer chaque projet en une expérience visuelle exceptionnelle qui dépasse les attentes, en alliant créativité audacieuse, innovation technique et excellence artisanale pour donner vie aux visions les plus ambitieuses de nos clients.',
    'about.vision.title': 'Notre Vision',
    'about.vision.desc': 'Devenir la référence incontournable en communication visuelle au Maroc et en Afrique, reconnue pour notre capacité à révolutionner l\'art de la signalétique et à créer des œuvres qui marquent durablement les esprits.',
    'about.cta.title1': 'CRÉONS ENSEMBLE',
    'about.cta.title2': 'VOTRE LÉGENDE',
    'about.cta.subtitle': 'Rejoignez l\'aventure créative et découvrez ce que nous pouvons accomplir ensemble',
    'about.cta.button': 'Démarrons votre projet',
    'contact.hero.badge': 'Parlons Création',
    'contact.hero.title1': 'CONNECTONS',
    'contact.hero.title2': 'NOS ÉNERGIES',
    'contact.hero.subtitle': 'Prêt à transformer vos idées en réalité visuelle ? Contactez-nous !',
    'contact.form.title': 'Démarrons Votre Projet',
    'contact.form.subtitle': 'Partagez-nous votre vision et nous la transformerons en chef-d\'œuvre visuel.',
    'contact.form.name': 'Nom complet',
    'contact.form.company': 'Entreprise',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Téléphone',
    'contact.form.project': 'Type de projet',
    'contact.form.message': 'Décrivez votre vision',
    'contact.form.submit': 'Envoyer ma demande',
    'contact.phone.title': 'Téléphone',
    'contact.phone.desc': 'Appelez-nous directement',
    'contact.email.title': 'Email',
    'contact.email.desc': 'Écrivez-nous',
    'contact.address.title': 'Adresse',
    'contact.address.desc': 'Visitez notre atelier',
    'contact.hours.title': 'Horaires',
    'contact.hours.desc': 'Nos heures d\'ouverture',
    'contact.whatsapp': 'Chatter sur WhatsApp',
    'contact.map.title': 'Trouvez-nous',
    'contact.form.name.label': 'Nom complet',
    'contact.form.name.placeholder': 'Votre nom',
    'contact.form.company.label': 'Entreprise',
    'contact.form.company.placeholder': 'Nom de votre entreprise',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'votre@email.com',
    'contact.form.phone.label': 'Téléphone',
    'contact.form.phone.placeholder': '+212 X XX XX XX XX',
    'contact.form.project.label': 'Type de projet',
    'contact.form.project.placeholder': 'Sélectionnez votre besoin',
    'contact.form.project.option1': 'Conception & Développement',
    'contact.form.project.option2': 'Produits PLV Retail',
    'contact.form.project.option3': 'Fournitures Saisonnières',
    'contact.form.project.option4': 'Habillage & Signalétique',
    'contact.form.project.option5': 'Autre projet créatif',
    'contact.form.message.label': 'Décrivez votre vision',
    'contact.form.message.placeholder': 'Partagez-nous votre idée, vos objectifs, votre budget approximatif...',
    'contact.form.submit.text': 'Envoyer ma demande',
    'contact.form.send': 'Envoyer ma demande',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.toggle': 'Ajouter des spécifications détaillées à ma demande',
    'contact.form.service.type': 'Type de service',
    'contact.form.service.printing': 'Impression',
    'contact.form.service.cutting': 'Découpe Plotter',
    'contact.form.service.cnc': 'CNC',
    'contact.form.service.laser': 'Laser',
    'contact.form.material': 'Matériau',
    'contact.form.size': 'Dimensions (L × H)',
    'contact.form.quantity': 'Quantité',
    'contact.form.indoor_outdoor': 'Usage',
    'contact.form.indoor': 'Intérieur',
    'contact.form.outdoor': 'Extérieur',
    'contact.form.finishing': 'Finition',
    'contact.form.artwork_ready': 'Visuel prêt à imprimer ?',
    'contact.form.yes': 'Oui',
    'contact.form.no': 'Non',
    'contact.form.thickness': 'Épaisseur',
    'contact.form.colors': 'Couleur(s) du vinyle',
    'contact.form.cutting_application': 'Service',
    'contact.form.cutting_only': 'Découpe uniquement',
    'contact.form.cutting_application_both': 'Découpe + Pose',
    'contact.form.design_ready': 'Fichier de conception prêt ?',
    'contact.form.cnc_finishing': 'Finition CNC',
    'contact.form.job_type': 'Type de travail',
    'contact.form.cutting': 'Découpe',
    'contact.form.engraving': 'Gravure',
    'contact.form.both': 'Les deux',
    'contact.form.detail_level': 'Niveau de détail',
    'contact.form.high_resolution': 'Haute résolution',
    'contact.form.standard': 'Standard',
    'contact.info.title': 'Informations de Contact',
    'contact.info.subtitle': 'Plusieurs moyens de nous joindre pour concrétiser vos projets',
    'contact.info.phone.title': 'Téléphone',
    'contact.info.phone.value': '+212 5 39 40 31 33',
    'contact.info.email.title': 'Email',
    'contact.info.email.value': 'contact@signatech.ma',
    'contact.info.address.title': 'Adresse',
    'contact.info.address.value': 'Zone Industrielle Gzenaya, Lot 376, Tanger, Maroc',
    'contact.info.hours.title': 'Horaires',
    'contact.info.hours.value': 'Lun-Ven: 8h-18h | Sam: 8h-13h',
    'contact.hours.mon_fri': 'Lun - Ven: 8h00 - 18h00',
    'contact.hours.saturday': 'Samedi: 8h00 - 13h00',
    'contact.hours.sunday': 'Dimanche: Fermé',
    'contact.map.placeholder': 'Carte Google Maps à intégrer',
    'services.hero.badge': 'Nos Super-pouvoirs',
    'services.hero.title1': 'SERVICES',
    'services.hero.title2': 'EXTRAORDINAIRES',
    'services.hero.subtitle': 'Chaque service est une nouvelle aventure créative où nous repoussons les limites du possible',
    'services.design.subtitle': 'Créativité sur mesure',
    'services.design.highlight': `${yearsOfExperience} années d\'expertise créative`,
    'services.retail.subtitle': 'Expériences d\'achat immersives',
    'services.retail.highlight': '500+ projets retail réalisés',
    'services.seasonal.subtitle': 'Campagnes événementielles',
    'services.seasonal.highlight': 'Réactivité 24h/48h',
    'services.signage.subtitle': 'Transformation d\'espaces',
    'services.signage.highlight': 'Garantie 5 ans sur nos installations',
    'services.process.badge': 'Notre Processus Créatif',
    'services.process.title1': 'DE L\'IDÉE À LA',
    'services.process.title2': 'RÉALISATION',
    'services.process.step1.title': 'Écoute & Analyse',
    'services.process.step1.desc': 'Compréhension approfondie de vos besoins et objectifs',
    'services.process.step2.title': 'Conception Créative',
    'services.process.step2.desc': 'Développement de concepts innovants et sur mesure',
    'services.process.step3.title': 'Validation & Prototype',
    'services.process.step3.desc': 'Tests et ajustements pour garantir la perfection',
    'services.process.step4.title': 'Réalisation & Livraison',
    'services.process.step4.desc': 'Production et installation avec suivi qualité',
    'services.cta.title1': 'CRÉONS VOTRE',
    'services.cta.title2': 'CHEF-D\'ŒUVRE',
    'services.cta.subtitle': 'Quel que soit votre défi créatif, nous avons la solution pour le transformer en succès',
    'services.cta.button': 'Discutons de votre projet',
    // Admin translations
    'admin.notifications.enabled': 'Activées',
    'admin.notifications.disabled': 'Désactivées',
    'admin.notifications.enable': 'Activer',
    'admin.notifications.disable': 'Désactiver',
    'admin.notifications.email': 'Notifications par email',
    'admin.total_users': 'Total Users',
    'admin.total_submissions': 'Total Submissions',
    'admin.admin_users': 'Admin Users',
    'admin.total_admins': 'Total admins',
    'admin.all_statuses': 'Tous les statuts',
    'admin.pending': 'En attente',
    'admin.completed': 'Terminé',
    'admin.reviews': 'Avis',
    'admin.contact_settings': 'Paramètres de Contact',
    'admin.registered_users': 'Registered Users',
    // Rating translations
    'rating.manage_reviews': 'Gestion des Avis',
    'rating.approved': 'Approuvé',
    'rating.pending': 'En attente',
    'rating.featured': 'Mis en avant',
    'rating.hide': 'Masquer',
    'rating.approve': 'Approuver',
    'rating.remove': 'Retirer',
    'rating.feature': 'Mettre en avant',
    'rating.no_reviews': 'Aucun avis pour le moment',
    'rating.status_updated': 'Statut mis à jour',
    'rating.status_updated_desc': 'Le statut de l\'avis a été modifié',
    'rating.delete_confirm': 'Êtes-vous sûr de vouloir supprimer cet avis ?',
    'rating.deleted': 'Avis supprimé',
    'rating.deleted_desc': 'L\'avis a été supprimé avec succès',
    'rating.delete_error': 'Impossible de supprimer l\'avis',
    'rating.update_error': 'Impossible de mettre à jour le statut',
    'rating.customer_review': 'Avis client',
    'rating.thank_you': 'Merci pour votre avis!',
    'rating.already_rated': 'Vous avez déjà donné votre avis. Un seul avis par client est autorisé.',
    'rating.not_eligible': 'Pas encore éligible',
    'rating.eligibility_desc': 'Vous pourrez donner votre avis une fois qu\'une de vos demandes sera terminée.',
    'rating.give_review': 'Donnez votre avis',
    'rating.send_review': 'Envoyer mon avis',
    'rating.send_error': 'Impossible d\'envoyer votre avis',
    'rating.view_all': 'Voir tous les avis',
    'rating.reviews': 'avis',
    'rating.customer_reviews': 'Avis Clients',
    'rating.all_reviews': 'Tous les avis',
    // File upload translations
    'contact.file_upload.label': 'Télécharger votre fichier de conception',
    'contact.file_upload.drag_drop': 'Glissez-déposez votre fichier ici ou cliquez pour parcourir',
    'contact.file_upload.accepted_formats': 'Formats acceptés: SVG, DXF, AI, PDF, EPS, G-code',
    'contact.file_upload.max_size': 'Taille maximale: 10 MB',
    'contact.file_upload.invalid_type': 'Type de fichier non supporté',
    'contact.file_upload.too_large': 'Le fichier est trop volumineux (max 10 MB)',
    'contact.file_upload.uploading': 'Téléchargement...',
    'contact.file_upload.uploaded': 'Fichier téléchargé avec succès',
    'contact.file_upload.optional': '(Optionnel)',
    'contact.file_upload.remove': 'Supprimer le fichier',
    'contact.file_upload.selected': 'Fichier sélectionné',
    // Error page translations
    'error.page_not_found': 'Oups ! Page non trouvée',
    'error.return_home': 'Retour à l\'accueil',
    // Debug page translations
    'debug.page_title': 'Page de Débogage',
    'debug.auth_status': 'Statut d\'Authentification',
    'debug.loading': 'Chargement',
    'debug.authenticated': 'Authentifié',
    'debug.user': 'Utilisateur',
    'debug.token': 'Token',
    'debug.yes': 'Oui',
    'debug.no': 'Non',
    'debug.not_logged_in': 'Non connecté',
    'debug.present': 'Présent',
    'debug.not_found': 'Non trouvé',
    'debug.api_test': 'Test API',
    'debug.status': 'Statut',
    'debug.response': 'Réponse',
    'debug.test_api_connection': 'Tester la connexion API',
    'debug.environment': 'Environnement',
    'debug.api_url': 'URL de l\'API',
    'debug.mode': 'Mode',
    'debug.browser': 'Navigateur',
    'debug.status_not_checked': 'Non vérifié',
    'debug.checking': 'Vérification...',
    'debug.success': 'Succès',
    'debug.error': 'Erreur',
    'debug.failed': 'Échec',
    'debug.unknown_error': 'Erreur inconnue',
    // Auth translations
    'auth.forgot_password.title': 'Mot de passe oublié - SignaTech',
    'auth.forgot_password.description': 'Réinitialisez votre mot de passe SignaTech',
    'auth.forgot_password.email_title': 'Mot de passe oublié',
    'auth.forgot_password.verification_title': 'Vérification',
    'auth.forgot_password.new_password_title': 'Nouveau mot de passe',
    'auth.forgot_password.email_desc': 'Entrez votre email pour recevoir un code de vérification',
    'auth.forgot_password.code_desc': 'Entrez le code à 6 chiffres envoyé à votre email',
    'auth.forgot_password.password_desc': 'Créez votre nouveau mot de passe',
    'auth.forgot_password.email_label': 'Email',
    'auth.forgot_password.email_placeholder': 'votre@email.com',
    'auth.forgot_password.code_label': 'Code de vérification',
    'auth.forgot_password.code_placeholder': '123456',
    'auth.forgot_password.password_label': 'Nouveau mot de passe',
    'auth.forgot_password.password_placeholder': '••••••••',
    'auth.forgot_password.confirm_password_label': 'Confirmer le mot de passe',
    'auth.forgot_password.confirm_password_placeholder': '••••••••',
    'auth.forgot_password.send_code': 'Envoyer le code',
    'auth.forgot_password.sending': 'Envoi...',
    'auth.forgot_password.verify_code': 'Vérifier le code',
    'auth.forgot_password.verifying': 'Vérification...',
    'auth.forgot_password.reset_password': 'Réinitialiser le mot de passe',
    'auth.forgot_password.updating': 'Mise à jour...',
    'auth.forgot_password.back_to_login': 'Retour à la connexion',
    'auth.forgot_password.server_unavailable': 'Serveur indisponible. Vérifiez que le serveur est démarré.',
    'auth.forgot_password.connection_error': 'Impossible de se connecter au serveur. Vérifiez que le serveur est démarré.',
    'auth.forgot_password.server_error': 'Serveur indisponible',
    'auth.forgot_password.unknown_error': 'Une erreur est survenue',
    'auth.forgot_password.passwords_no_match': 'Les mots de passe ne correspondent pas',
    // Portfolio translations
    'portfolio.our_work': 'Nos Réalisations',
    'portfolio.loading': 'Chargement...',
    'portfolio.organized_portfolio': 'Découvrez notre portfolio organisé par catégories',
    'portfolio.loading_projects': 'Chargement des projets...',
    'portfolio.no_projects': 'Aucun projet disponible pour le moment.',
    // Rating additional translations
    'rating.discover_feedback': 'Découvrez ce que nos clients pensent de nos services',
    'rating.checking': 'Vérification...',
    'rating.login_required': 'Connexion requise',
    'rating.login_required_desc': 'Vous devez être connecté pour donner un avis sur nos services.',
    'rating.rating_label': 'Note',
    'rating.comment_label': 'Commentaire',
    'rating.comment_placeholder': 'Partagez votre expérience...',
    'rating.characters': 'caractères',
    'rating.minimum': 'minimum',
    'rating.sending': 'Envoi...',
    // Contact additional translations
    'contact.logged_in_as': 'Connecté en tant que',
    'contact.info_prefilled': 'Vos informations sont pré-remplies',
    'contact.tip': 'Conseil',
    'contact.create_account_tip': 'Créez un compte pour une expérience plus rapide!',
    'contact.logged_users_benefit': 'Les utilisateurs connectés n\'ont pas besoin de ressaisir leurs informations.',
    'contact.add_service': 'Ajouter un Service',
    'contact.required_services': 'Services Requis',
    'contact.service': 'Service',
    'contact.not_specified': 'Non spécifié',
    'contact.material': 'Matériau',
    'contact.size': 'Taille',
    'contact.quantity': 'Quantité',
    'contact.edit': 'Modifier',
    'contact.delete': 'Supprimer',
    'contact.find_us': 'Trouvez-nous',
    'contact.location': 'Zone Industrielle Gzenaya, Tanger',
    'contact.edit_service': 'Modifier le Service',
    'contact.service_type': 'Type de Service',
    'contact.select_service': 'Sélectionnez un service',
    'contact.printing': 'Impression',
    'contact.cutting': 'Découpe',
    'contact.cnc': 'CNC',
    'contact.laser': 'Laser',
    'contact.size_example': 'ex: 100cm × 70cm',
    'contact.quantity_example': 'ex: 10 pièces',
    'contact.thickness': 'Épaisseur',
    'contact.thickness_example': 'ex: 3mm',
    'contact.colors': 'Couleurs',
    'contact.colors_example': 'Rouge, bleu, blanc...',
    'contact.finishing': 'Finition',
    'contact.finishing_example': 'Mat, brillant, laminé, monté...',
    'contact.cancel': 'Annuler',
    'contact.add': 'Ajouter',
    // Additional rating translations
    'rating.view_less': 'Voir moins',
    'rating.signatech_client': 'Client SignaTech',
    'rating.client_evaluations': 'Évaluations Clients',
    // Common translations
    'common.error': 'Erreur',
    // Auth translations
    'auth.login': 'Connexion',
    'auth.login_desc': 'Connectez-vous pour accéder au formulaire',
    'auth.email': 'Email',
    'auth.email_placeholder': 'votre@email.com',
    'auth.password': 'Mot de passe',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.password_placeholder': '••••••••',
    'auth.logging_in': 'Connexion...',
    'auth.login_button': 'Se connecter',
    'auth.or': 'Ou',
    'auth.continue_google': 'Continuer avec Google',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.create_account': 'Créer un compte',
    // Admin page translations
    'admin.dashboard': 'Tableau de bord',
    'admin.images': 'Images',
    'admin.files': 'Fichiers',
    'admin.projects': 'Projets',
    'admin.theme': 'Thème',
    'admin.contact': 'Contact',
    'admin.admins': 'Admins',
    'admin.users': 'Utilisateurs',
    'admin.submissions': 'Demandes',
    'admin.panel': 'Panneau Admin',
    'admin.dashboard_title': 'Tableau de bord Admin',
    'admin.dashboard_desc': 'Gérer les utilisateurs et voir les demandes de contact',
    'admin.notifications_updated': 'Notifications mises à jour',
    'admin.notifications_enabled': 'Notifications activées avec succès',
    'admin.notifications_disabled': 'Notifications désactivées avec succès',
    'admin.loading_admin_data': 'Chargement des données admin...',
    'admin.loading_images': 'Chargement des images...',
    'admin.loading_projects': 'Chargement des projets...',
    'admin.loading_theme_settings': 'Chargement des paramètres de thème...',
    'admin.loading_contact_settings': 'Chargement des paramètres de contact...',
    'admin.loading_reviews': 'Chargement des avis...',
    'admin.admin_management': 'Gestion des Administrateurs',
    'admin.create_admin': 'Créer un Admin',
    'admin.name': 'Nom',
    'admin.email': 'Email',
    'admin.created': 'Créé',
    
    'admin.company': 'Entreprise',
    'admin.phone': 'Téléphone',
    'admin.role': 'Rôle',
    'admin.registered': 'Inscrit',
    'admin.view_details': 'Voir les détails',
    'admin.delete_user': 'Supprimer l\'utilisateur',
    'admin.contact_submissions': 'Demandes de Contact',
    'admin.user_requests': 'Demandes de {name} ({count} demande{plural})',
    'admin.no_requests_found': 'Aucune demande trouvée pour cet utilisateur.',
    'admin.create_new_admin': 'Créer un nouvel administrateur',
    'admin.admin_name': 'Nom de l\'admin',
    'admin.admin_email': 'Email de l\'admin',
    'admin.password': 'Mot de passe',
    'admin.minimum_characters': 'Minimum 6 caractères',
    'admin.cancel': 'Annuler',
    'admin.create': 'Créer',
    'admin.confirm_delete': 'Confirmer la suppression',
    'admin.confirm_delete_user': 'Êtes-vous sûr de vouloir supprimer le compte de {name} ? Cette action est irréversible.',
    'admin.delete': 'Supprimer',
    'admin.admin_created': 'Admin créé',
    'admin.admin_created_success': 'Le nouvel administrateur a été créé avec succès',
    'admin.user_deleted': 'Utilisateur supprimé',
    'admin.user_deleted_success': 'L\'utilisateur a été supprimé avec succès',
    'admin.search_placeholder': 'Rechercher utilisateurs, demandes ou contenu...',
    'admin.access_denied': 'Accès refusé',
    'admin.no_permission': 'Vous n\'avez pas la permission d\'accéder à cette page.',
    // Contact Settings translations
    'contact_settings.company_info': 'Informations de l\'entreprise',
    'contact_settings.company_name': 'Nom de l\'entreprise',
    'contact_settings.company_tagline': 'Slogan/Tagline',
    'contact_settings.coordinates': 'Coordonnées',
    'contact_settings.email_address': 'Adresse Email',
    'contact_settings.telephone': 'Téléphone',
    'contact_settings.whatsapp': 'WhatsApp',
    'contact_settings.address': 'Adresse',
    'contact_settings.address_french': 'Adresse (Français)',
    'contact_settings.address_english': 'Adresse (English)',
    'contact_settings.opening_hours': 'Horaires d\'ouverture',
    'contact_settings.short_hours_french': 'Horaires courts (Français)',
    'contact_settings.short_hours_english': 'Horaires courts (English)',
    'contact_settings.detailed_hours_french': 'Horaires détaillés (Français)',
    'contact_settings.detailed_hours_english': 'Horaires détaillés (English)',
    'contact_settings.separate_lines': 'Séparez les lignes avec | (pipe)',
    'contact_settings.saving': 'Sauvegarde...',
    'contact_settings.save': 'Sauvegarder',
    'contact_settings.saved': 'Paramètres sauvegardés',
    'contact_settings.saved_success': 'Les informations de contact ont été mises à jour avec succès.',
    'contact_settings.save_error': 'Impossible de sauvegarder les paramètres.',
    // Image Manager translations
    'image_manager.title': 'Gestion des Images',
    'image_manager.category': 'Catégorie',
    'image_manager.all_categories': 'Toutes les catégories',
    'image_manager.refresh': 'Actualiser',
    'image_manager.add_new_image': 'Ajouter une nouvelle image',
    'image_manager.file': 'Fichier',
    'image_manager.category_placeholder': 'logo, hero, portfolio, etc.',
    'image_manager.uploading': 'Upload...',
    'image_manager.add': 'Ajouter',
    'image_manager.size': 'Taille',
    'image_manager.replace': 'Remplacer',
    'image_manager.no_images': 'Aucune image trouvée',
    'image_manager.access_denied': 'Accès refusé. Vous devez être administrateur.',
    'image_manager.user': 'Utilisateur',
    'image_manager.admin': 'Admin',
    'image_manager.yes': 'Oui',
    'image_manager.no': 'Non',
    'image_manager.token': 'Token',
    'image_manager.present': 'Présent',
    'image_manager.missing': 'Manquant',
    'image_manager.reconnect': 'Se reconnecter',
    'image_manager.image_added': 'Image ajoutée avec succès!',
    'image_manager.upload_error': 'Erreur d\'upload',
    'image_manager.connection_error': 'Erreur de connexion lors de l\'upload',
    'image_manager.delete_confirm': 'Êtes-vous sûr de vouloir supprimer cette image ?',
    'image_manager.image_deleted': 'Image supprimée avec succès!',
    'image_manager.delete_error': 'Erreur de suppression',
    'image_manager.connection_delete_error': 'Erreur de connexion lors de la suppression',
    'image_manager.image_replaced': 'Image remplacée avec succès!',
    'image_manager.replace_error': 'Erreur de remplacement',
    'image_manager.connection_replace_error': 'Erreur de connexion lors du remplacement',
    'image_manager.server_connection_error': 'Erreur de connexion au serveur',
    // Organized Image Manager translations
    'organized_images.title': 'Gestion Organisée des Images',
    'organized_images.description': 'Chaque section correspond à un usage spécifique sur le site. L\'ordre des images est important pour l\'affichage.',
    'organized_images.critical': 'Critique',
    'organized_images.important': 'Important',
    'organized_images.standard': 'Standard',
    'organized_images.critical_desc': 'Affichage immédiat',
    'organized_images.important_desc': 'Pages principales',
    'organized_images.standard_desc': 'Galeries',
    'organized_images.site_logo': 'Logo du Site',
    'organized_images.homepage': 'Page d\'Accueil',
    'organized_images.about_page': 'Page À Propos',
    'organized_images.portfolio_carousel': 'Portfolio Carousel',
    'organized_images.logo_desc': 'Logo principal affiché dans l\'en-tête et utilisé comme favicon (icône de l\'onglet)',
    'organized_images.homepage_desc': 'Images principales de la page d\'accueil (hero + 2 aperçus portfolio)',
    'organized_images.about_desc': 'Image de l\'équipe utilisée dans la section histoire',
    'organized_images.portfolio_desc': 'Images pour le système de carousel organisé par sections',
    'organized_images.limit_reached': 'Limite atteinte ({max} images max). Supprimez une image pour en ajouter une nouvelle.',
    'organized_images.favicon_info': 'Favicon Automatique',
    'organized_images.favicon_desc': 'Cette image sera automatiquement utilisée comme favicon (icône dans l\'onglet du navigateur).',
    'organized_images.favicon_formats': 'Formats recommandés: PNG, SVG, ICO. L\'image sera redimensionnée automatiquement par le navigateur.',
    'organized_images.hero_info': 'Cette section est limitée à 3 images spécifiques pour la page d\'accueil:',
    'organized_images.hero_main': 'Image principale (Hero) - Affichée en haut de la page d\'accueil',
    'organized_images.hero_project1': 'Aperçu projet 1 (Façade) - Affichée dans la section portfolio (1ère carte)',
    'organized_images.hero_project2': 'Aperçu projet 2 (Artisanat) - Affichée dans la section portfolio (3ème carte)',
    'organized_images.main_image': 'Principale',
    'organized_images.main_hero': 'Image principale (Hero)',
    'organized_images.project_preview1': 'Aperçu projet 1 (Façade)',
    'organized_images.project_preview2': 'Aperçu projet 2 (Artisanat)',
    'organized_images.team_image': 'Image équipe',
    'organized_images.no_images_section': 'Aucune image dans cette section',
    'organized_images.carousel_organization': 'Organisation du Carousel',
    'organized_images.new_section': 'Nouvelle Section',
    'organized_images.section_name_placeholder': 'Nom de la section (ex: Projets Web)',
    'organized_images.display_order': 'Ordre d\'affichage',
    'organized_images.create': 'Créer',
    'organized_images.project': 'Projet',
    'organized_images.project_title': 'Titre du projet',
    'organized_images.description_optional': 'Description (optionnelle)',
    'organized_images.select_image': 'Sélectionner une image',
    'organized_images.no_projects_section': 'Aucun projet dans cette section',
    'organized_images.delete_project_confirm': 'Supprimer ce projet ?',
    'organized_images.no_sections': 'Aucune section créée. Créez votre première section pour organiser vos projets.',
    'organized_images.carousel_system_title': 'Système de Carousel Portfolio',
    'organized_images.carousel_system_desc': 'Le portfolio utilise maintenant un système de carousel organisé par sections. Ajoutez vos images dans la section "Portfolio Carousel" ci-dessus, puis organisez-les en projets.',
    'organized_images.carousel_step1': 'Uploadez vos images dans la section Portfolio Carousel',
    'organized_images.carousel_step2': 'Créez des sections (ex: "Projets Web", "Applications Mobiles")',
    'organized_images.carousel_step3': 'Ajoutez des projets à chaque section avec titre, description et image',
    'organized_images.carousel_step4': 'Les visiteurs verront un carousel moderne avec vos projets organisés',
    'organized_images.image_updated': 'Image mise à jour avec succès! Actualisez la page du site pour voir les changements.',
    'organized_images.image_replaced': 'Image remplacée avec succès! Actualisez la page du site pour voir les changements.',
    'organized_images.access_denied': 'Accès refusé',
    // Project Manager translations
    'project_manager.title': 'Gestion des Projets',
    'project_manager.new_section': 'Nouvelle Section',
    'project_manager.section_name': 'Nom de la section',
    'project_manager.active': 'Actif',
    'project_manager.inactive': 'Inactif',
    'project_manager.projects': 'projets',
    'project_manager.new_project': 'Nouveau Projet',
    'project_manager.project_title': 'Titre du projet',
    'project_manager.description_optional': 'Description (optionnelle)',
    'project_manager.select_existing_image': 'Sélectionner une image existante',
    'project_manager.upload_new': 'Upload New',
    'project_manager.choose_existing_or_upload': 'Choisissez une image existante ou uploadez-en une nouvelle depuis votre PC',
    'project_manager.display_order': 'Ordre d\'affichage',
    'project_manager.delete_section_confirm': 'Êtes-vous sûr de vouloir supprimer cette section et tous ses projets ?',
    'project_manager.delete_project_confirm': 'Êtes-vous sûr de vouloir supprimer ce projet ?',
    'project_manager.image_updated': 'Image updated successfully!',
    'project_manager.image_update_failed': 'Failed to update image',
    'project_manager.image_upload_error': 'Error uploading image. Please try again.',
    'project_manager.image_uploaded': 'Image uploaded successfully!',
    'project_manager.image_upload_failed': 'Failed to upload image',
    'project_manager.replace': 'Replace',
    'project_manager.add': 'Add',
    // Theme Settings translations
    'theme_settings.title': 'Paramètres de Thème',
    'theme_settings.loading': 'Chargement des paramètres de thème...',
    'theme_settings.color_presets': 'Préréglages de Couleurs',
    'theme_settings.default_purple': 'Violet par Défaut',
    'theme_settings.ocean_blue': 'Bleu Océan',
    'theme_settings.forest_green': 'Vert Forêt',
    'theme_settings.sunset_orange': 'Orange Coucher de Soleil',
    'theme_settings.custom_colors': 'Couleurs Personnalisées',
    'theme_settings.primary_color': 'Couleur Primaire',
    'theme_settings.accent_color': 'Couleur d\'Accent',
    'theme_settings.background': 'Arrière-plan',
    'theme_settings.card_background': 'Arrière-plan des Cartes',
    'theme_settings.text_color': 'Couleur du Texte',
    'theme_settings.gradient_settings': 'Paramètres de Dégradé',
    'theme_settings.gradient_start': 'Début du Dégradé',
    'theme_settings.gradient_end': 'Fin du Dégradé',
    'theme_settings.gradient_direction': 'Direction du Dégradé',
    'theme_settings.diagonal_down_right': 'Diagonale Bas-Droite (↘)',
    'theme_settings.top_to_bottom': 'Haut vers Bas (↓)',
    'theme_settings.left_to_right': 'Gauche vers Droite (→)',
    'theme_settings.diagonal_up_right': 'Diagonale Haut-Droite (↗)',
    'theme_settings.right_to_left': 'Droite vers Gauche (←)',
    'theme_settings.bottom_to_top': 'Bas vers Haut (↑)',
    'theme_settings.diagonal_down_left': 'Diagonale Bas-Gauche (↙)',
    'theme_settings.diagonal_up_left': 'Diagonale Haut-Gauche (↖)',
    'theme_settings.theme_history': 'Historique des Thèmes',
    'theme_settings.theme': 'Thème',
    'theme_settings.stop_preview': 'Arrêter l\'Aperçu',
    'theme_settings.preview': 'Aperçu',
    'theme_settings.apply_theme': 'Appliquer le Thème',
    'theme_settings.saving': 'Sauvegarde...',
    'theme_settings.reset': 'Réinitialiser',
    'theme_settings.preview_mode_active': 'Mode Aperçu Actif',
    // User Manager translations
    'user_manager.title': 'Gestion des Utilisateurs',
    'user_manager.users': 'utilisateurs',
    'user_manager.admin': 'Admin',
    'user_manager.client': 'Client',
    'user_manager.registered_on': 'Inscrit le',
    'user_manager.delete': 'Supprimer',
    'user_manager.your_account': 'Votre compte',
    'user_manager.no_users': 'Aucun utilisateur trouvé',
    'user_manager.delete_confirm': 'Êtes-vous sûr de vouloir supprimer le compte de {name} ? Cette action est irréversible.',
    'user_manager.user_deleted': 'Utilisateur supprimé avec succès',
    'user_manager.delete_error': 'Erreur lors de la suppression'
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.quote': 'Free Quote',
    'hero.badge': `${yearsOfExperience} years of experience`,
    'hero.title1': 'CREATIVE',
    'hero.title2': 'SOLUTIONS',
    'hero.subtitle': 'We transform your ideas into',
    'hero.subtitle.highlight': 'effective visual solutions',
    'hero.subtitle.end': 'that strengthen your brand',
    'hero.cta.primary': 'Create Together',
    'hero.cta.secondary': 'Discover Our Creations',
    'stats.experience': 'Years of Experience',
    'stats.projects': 'Projects Completed',
    'stats.clients': 'Satisfied Clients',
    'stats.solutions': 'Custom Solutions',
    'services.badge': 'Our Services',
    'services.title1': 'PROFESSIONAL',
    'services.title2': 'SOLUTIONS',
    'services.subtitle': 'Comprehensive services tailored to your visual communication and POS needs',
    'services.design.title': 'Design & Development',
    'services.design.desc': 'Custom creation of your communication materials and POS displays with our experienced design team.',
    'services.design.desc_detailed': 'Our experienced design team transforms your ideas into exceptional visual creations, from initial concept to final realization.',
    'services.design.feature1': 'Custom Design',
    'services.design.feature2': 'Prototyping',
    'services.design.feature3': 'Client Validation',
    'services.design.feature4': 'Strategic Consultation',
    'services.design.feature5': 'Research and Trends',
    'services.retail.title': 'Retail POS Products',
    'services.retail.desc': 'Complete solutions for your points of sale: displays, stands, commercial furniture.',
    'services.retail.desc_detailed': 'Complete solutions to optimize your points of sale with displays, stands and commercial furniture that capture attention and stimulate sales.',
    'services.retail.feature1': 'Custom Displays',
    'services.retail.feature2': 'Retail Furniture',
    'services.retail.feature3': 'Interactive Displays',
    'services.retail.feature4': 'Modular Solutions',
    'services.retail.feature5': 'Space Planning',
    'services.seasonal.title': 'Seasonal Supplies',
    'services.seasonal.desc': 'Promotional campaigns and temporary supports for your special events.',
    'services.seasonal.desc_detailed': 'Temporary promotional supports and seasonal decorations that create events and leave lasting impressions during your special campaigns.',
    'services.seasonal.feature1': 'Event Campaigns',
    'services.seasonal.feature2': 'Temporary Supports',
    'services.seasonal.feature3': 'Seasonal Decoration',
    'services.seasonal.feature4': 'Special Events',
    'services.seasonal.feature5': 'Express Installation',
    'services.signage.title': 'Cladding & Signage',
    'services.signage.desc': 'Complete transformation of your facades and spaces with our signage expertise.',
    'services.signage.desc_detailed': 'Complete metamorphosis of your facades and spaces with our expertise in signage, illuminated signs and architectural cladding.',
    'services.signage.feature1': 'Facade Cladding',
    'services.signage.feature2': 'Illuminated Signs',
    'services.signage.feature3': 'Directional Signage',
    'services.signage.feature4': 'Totems and Pylons',
    'services.signage.feature5': 'Floor Marking',
    'services.cta': 'Explore Our Talents',
    'portfolio.badge': 'Our Work',
    'portfolio.title1': 'COMPLETED',
    'portfolio.title2': 'PROJECTS',
    'portfolio.subtitle': 'Discover our projects that combine creativity with commercial effectiveness',
    'portfolio.facade.title': 'Revolutionary Facade',
    'portfolio.facade.desc': 'A spectacular transformation that redefines urban visual identity.',
    'portfolio.plv.title': 'Revolutionary POS',
    'portfolio.plv.desc': 'Immersive shopping experiences that transform every visit into an adventure.',
    'portfolio.craft.title': 'Artisanal Mastery',
    'portfolio.craft.desc': 'Technical expertise serving bold creative visions.',
    'portfolio.cta': 'Explore All Our Works',
    'testimonials.badge': 'Client Testimonials',
    'testimonials.title1': 'CLIENT',
    'testimonials.title2': 'FEEDBACK',
    'testimonials.subtitle': 'See what our clients say about our work',
    'testimonials.cocacola.role': 'Marketing Manager',
    'testimonials.cocacola.content': 'Signa Tech transformed our points of sale with exceptional POS solutions. Their creativity and professionalism are remarkable.',
    'testimonials.juver.role': 'Commercial Director',
    'testimonials.juver.content': 'A trusted partner for several years. The quality of their work and respect for deadlines are exemplary.',
    'testimonials.expleo.role': 'Project Manager',
    'testimonials.expleo.content': 'Signa Tech\'s technical expertise and innovation have significantly improved our commercial visibility.',
    'cta.title1': 'START YOUR',
    'cta.title2': 'PROJECT',
    'cta.title3': 'with us',
    'cta.subtitle': 'Ready to develop your',
    'cta.subtitle.highlight': 'project',
    'cta.subtitle.end': 'together?',
    'cta.primary': 'Create the Future',
    'cta.secondary': 'Talk Now',
    'company.name': 'Signa Tech',
    'company.tagline': 'POS & Signage Solutions',
    'company.address': 'Industrial Zone Gzenaya lot 376, Tangier, Morocco',
    'footer.description': `For over ${yearsOfExperience} years, we have been creating creative and innovative communication solutions to strengthen your brand visibility.`,
    'footer.navigation': 'Navigation',
    'footer.services': 'Our Services',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'about.hero.badge': 'Our Story',
    'about.hero.title1': 'COMMUNICATION',
    'about.hero.title2': 'EXPERTS',
    'about.hero.subtitle': `${yearsOfExperience} years of experience in visual solutions and POS displays`,
    'about.story.badge': 'Our Journey',
    'about.story.title': `Our Story Over ${yearsOfExperience} Years`,
    'about.story.p1': 'Founded in Tangier, Signa Tech specializes in visual communication solutions and POS displays. We support our clients in developing their brand image.',
    'about.story.p2': 'Our work is designed to effectively meet your commercial objectives while respecting your visual identity.',
    'about.story.p3': 'With over 500 completed projects and the trust of prestigious clients like Coca-Cola, Juver and Expleo Group, we continue to innovate to push the boundaries of possibility.',
    'about.values.badge': 'Our Core Values',
    'about.values.title1': 'WHAT',
    'about.values.title2': 'DEFINES US',
    'about.values.quality.title': 'Quality Excellence',
    'about.values.quality.desc': 'We are committed to delivering creations of impeccable quality, consistently exceeding our clients\' expectations.',
    'about.values.confidentiality.title': 'Absolute Confidentiality',
    'about.values.confidentiality.desc': 'Your projects and ideas are protected with the utmost care. Discretion is at the heart of our client relationship.',
    'about.values.innovation.title': 'Bold Innovation',
    'about.values.innovation.desc': 'We constantly push creative boundaries to design solutions that make an impact and transform.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Transform every project into an exceptional visual experience that exceeds expectations, combining bold creativity, technical innovation and artisanal excellence to bring our clients\' most ambitious visions to life.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'Become the undisputed reference in visual communication in Morocco and Africa, recognized for our ability to revolutionize the art of signage and create works that leave lasting impressions.',
    'about.cta.title1': 'CREATE TOGETHER',
    'about.cta.title2': 'YOUR LEGEND',
    'about.cta.subtitle': 'Join the creative adventure and discover what we can accomplish together',
    'about.cta.button': 'Start Your Project',
    'contact.hero.badge': 'Let\'s Talk Creation',
    'contact.hero.title1': 'CONNECT OUR',
    'contact.hero.title2': 'ENERGIES',
    'contact.hero.subtitle': 'Ready to transform your ideas into visual reality? Contact us!',
    'contact.form.title': 'Start Your Project',
    'contact.form.subtitle': 'Share your vision with us and we\'ll transform it into a visual masterpiece.',
    'contact.form.name': 'Full Name',
    'contact.form.company': 'Company',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.project': 'Project Type',
    'contact.form.message': 'Describe Your Vision',
    'contact.form.submit': 'Send My Request',
    'contact.phone.title': 'Phone',
    'contact.phone.desc': 'Call us directly',
    'contact.email.title': 'Email',
    'contact.email.desc': 'Write to us',
    'contact.address.title': 'Address',
    'contact.address.desc': 'Visit our workshop',
    'contact.hours.title': 'Hours',
    'contact.hours.desc': 'Our opening hours',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.map.title': 'Find Us',
    'contact.form.name.label': 'Full Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.company.label': 'Company',
    'contact.form.company.placeholder': 'Your company name',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone.label': 'Phone',
    'contact.form.phone.placeholder': '+212 X XX XX XX XX',
    'contact.form.project.label': 'Project Type',
    'contact.form.project.placeholder': 'Select your need',
    'contact.form.project.option1': 'Design & Development',
    'contact.form.project.option2': 'Retail POS Products',
    'contact.form.project.option3': 'Seasonal Supplies',
    'contact.form.project.option4': 'Cladding & Signage',
    'contact.form.project.option5': 'Other creative project',
    'contact.form.message.label': 'Describe Your Vision',
    'contact.form.message.placeholder': 'Share your idea, objectives, approximate budget...',
    'contact.form.submit.text': 'Send My Request',
    'contact.form.send': 'Send My Request',
    'contact.form.sending': 'Sending...',
    'contact.form.toggle': 'Add detailed specifications to my request',
    'contact.form.service.type': 'Service Type',
    'contact.form.service.printing': 'Printing',
    'contact.form.service.cutting': 'Cutting Plotter',
    'contact.form.service.cnc': 'CNC',
    'contact.form.service.laser': 'Laser',
    'contact.form.material': 'Material',
    'contact.form.size': 'Size (W × H)',
    'contact.form.quantity': 'Quantity',
    'contact.form.indoor_outdoor': 'Usage',
    'contact.form.indoor': 'Indoor',
    'contact.form.outdoor': 'Outdoor',
    'contact.form.finishing': 'Finishing',
    'contact.form.artwork_ready': 'Ready-to-print artwork?',
    'contact.form.yes': 'Yes',
    'contact.form.no': 'No',
    'contact.form.thickness': 'Thickness',
    'contact.form.colors': 'Vinyl Color(s)',
    'contact.form.cutting_application': 'Service',
    'contact.form.cutting_only': 'Cutting only',
    'contact.form.cutting_application_both': 'Cutting + Application',
    'contact.form.design_ready': 'Design file ready?',
    'contact.form.cnc_finishing': 'CNC Finishing',
    'contact.form.job_type': 'Job Type',
    'contact.form.cutting': 'Cutting',
    'contact.form.engraving': 'Engraving',
    'contact.form.both': 'Both',
    'contact.form.detail_level': 'Detail Level',
    'contact.form.high_resolution': 'High Resolution',
    'contact.form.standard': 'Standard',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Multiple ways to reach us to bring your projects to life',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.value': '+212 5 39 40 31 33',
    'contact.info.email.title': 'Email',
    'contact.info.email.value': 'contact@signatech.ma',
    'contact.info.address.title': 'Address',
    'contact.info.address.value': 'Industrial Zone Gzenaya, Lot 376, Tangier, Morocco',
    'contact.info.hours.title': 'Hours',
    'contact.info.hours.value': 'Mon-Fri: 8am-6pm | Sat: 8am-1pm',
    'contact.hours.mon_fri': 'Mon - Fri: 8:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday: 8:00 AM - 1:00 PM',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.map.placeholder': 'Google Maps to be integrated',
    'services.hero.badge': 'Our Superpowers',
    'services.hero.title1': 'EXTRAORDINARY',
    'services.hero.title2': 'SERVICES',
    'services.hero.subtitle': 'Every service is a new creative adventure where we push the boundaries of possibility',
    'services.design.subtitle': 'Custom Creativity',
    'services.design.highlight': `${yearsOfExperience} years of creative expertise`,
    'services.retail.subtitle': 'Immersive Shopping Experiences',
    'services.retail.highlight': '500+ retail projects completed',
    'services.seasonal.subtitle': 'Event Campaigns',
    'services.seasonal.highlight': '24h/48h responsiveness',
    'services.signage.subtitle': 'Space Transformation',
    'services.signage.highlight': '5-year warranty on our installations',
    'services.process.badge': 'Our Creative Process',
    'services.process.title1': 'FROM IDEA TO',
    'services.process.title2': 'REALIZATION',
    'services.process.step1.title': 'Listen & Analyze',
    'services.process.step1.desc': 'Deep understanding of your needs and objectives',
    'services.process.step2.title': 'Creative Design',
    'services.process.step2.desc': 'Development of innovative and custom concepts',
    'services.process.step3.title': 'Validation & Prototype',
    'services.process.step3.desc': 'Testing and adjustments to guarantee perfection',
    'services.process.step4.title': 'Production & Delivery',
    'services.process.step4.desc': 'Production and installation with quality monitoring',
    'services.cta.title1': 'CREATE YOUR',
    'services.cta.title2': 'MASTERPIECE',
    'services.cta.subtitle': 'Whatever your creative challenge, we have the solution to transform it into success',
    'services.cta.button': 'Let\'s discuss your project',
    // Admin translations
    'admin.notifications.enabled': 'Enabled',
    'admin.notifications.disabled': 'Disabled',
    'admin.notifications.enable': 'Enable',
    'admin.notifications.disable': 'Disable',
    'admin.notifications.email': 'Email notifications',
    'admin.total_users': 'Total Users',
    'admin.total_submissions': 'Total Submissions',
    'admin.admin_users': 'Admin Users',
    'admin.total_admins': 'Total admins',
    'admin.all_statuses': 'All statuses',
    'admin.pending': 'Pending',
    'admin.completed': 'Completed',
    'admin.reviews': 'Reviews',
    'admin.contact_settings': 'Contact Settings',
    'admin.registered_users': 'Registered Users',
    // Rating translations
    'rating.manage_reviews': 'Manage Reviews',
    'rating.approved': 'Approved',
    'rating.pending': 'Pending',
    'rating.featured': 'Featured',
    'rating.hide': 'Hide',
    'rating.approve': 'Approve',
    'rating.remove': 'Remove',
    'rating.feature': 'Feature',
    'rating.no_reviews': 'No reviews yet',
    'rating.status_updated': 'Status updated',
    'rating.status_updated_desc': 'Review status has been updated',
    'rating.delete_confirm': 'Are you sure you want to delete this review?',
    'rating.deleted': 'Review deleted',
    'rating.deleted_desc': 'Review has been deleted successfully',
    'rating.delete_error': 'Unable to delete review',
    'rating.update_error': 'Unable to update status',
    'rating.customer_review': 'Customer Review',
    'rating.thank_you': 'Thank you for your review!',
    'rating.already_rated': 'You have already given your review. Only one review per customer is allowed.',
    'rating.not_eligible': 'Not yet eligible',
    'rating.eligibility_desc': 'You will be able to give your review once one of your requests is completed.',
    'rating.give_review': 'Give your review',
    'rating.send_review': 'Send my review',
    'rating.send_error': 'Unable to send your review',
    'rating.view_all': 'View all reviews',
    'rating.reviews': 'reviews',
    'rating.customer_reviews': 'Customer Reviews',
    'rating.all_reviews': 'All reviews',
    // File upload translations
    'contact.file_upload.label': 'Upload your design file',
    'contact.file_upload.drag_drop': 'Drag and drop your file here or click to browse',
    'contact.file_upload.accepted_formats': 'Accepted formats: SVG, DXF, AI, PDF, EPS, G-code',
    'contact.file_upload.max_size': 'Maximum size: 10 MB',
    'contact.file_upload.invalid_type': 'File type not supported',
    'contact.file_upload.too_large': 'File is too large (max 10 MB)',
    'contact.file_upload.uploading': 'Uploading...',
    'contact.file_upload.uploaded': 'File uploaded successfully',
    'contact.file_upload.optional': '(Optional)',
    'contact.file_upload.remove': 'Remove file',
    'contact.file_upload.selected': 'File selected',
    // Error page translations
    'error.page_not_found': 'Oops! Page not found',
    'error.return_home': 'Return to Home',
    // Debug page translations
    'debug.page_title': 'Debug Page',
    'debug.auth_status': 'Authentication Status',
    'debug.loading': 'Loading',
    'debug.authenticated': 'Authenticated',
    'debug.user': 'User',
    'debug.token': 'Token',
    'debug.yes': 'Yes',
    'debug.no': 'No',
    'debug.not_logged_in': 'Not logged in',
    'debug.present': 'Present',
    'debug.not_found': 'Not found',
    'debug.api_test': 'API Test',
    'debug.status': 'Status',
    'debug.response': 'Response',
    'debug.test_api_connection': 'Test API Connection',
    'debug.environment': 'Environment',
    'debug.api_url': 'API URL',
    'debug.mode': 'Mode',
    'debug.browser': 'Browser',
    'debug.status_not_checked': 'Not checked',
    'debug.checking': 'Checking...',
    'debug.success': 'Success',
    'debug.error': 'Error',
    'debug.failed': 'Failed',
    'debug.unknown_error': 'Unknown error',
    // Auth translations
    'auth.forgot_password.title': 'Forgot Password - SignaTech',
    'auth.forgot_password.description': 'Reset your SignaTech password',
    'auth.forgot_password.email_title': 'Forgot Password',
    'auth.forgot_password.verification_title': 'Verification',
    'auth.forgot_password.new_password_title': 'New Password',
    'auth.forgot_password.email_desc': 'Enter your email to receive a verification code',
    'auth.forgot_password.code_desc': 'Enter the 6-digit code sent to your email',
    'auth.forgot_password.password_desc': 'Create your new password',
    'auth.forgot_password.email_label': 'Email',
    'auth.forgot_password.email_placeholder': 'your@email.com',
    'auth.forgot_password.code_label': 'Verification Code',
    'auth.forgot_password.code_placeholder': '123456',
    'auth.forgot_password.password_label': 'New Password',
    'auth.forgot_password.password_placeholder': '••••••••',
    'auth.forgot_password.confirm_password_label': 'Confirm Password',
    'auth.forgot_password.confirm_password_placeholder': '••••••••',
    'auth.forgot_password.send_code': 'Send Code',
    'auth.forgot_password.sending': 'Sending...',
    'auth.forgot_password.verify_code': 'Verify Code',
    'auth.forgot_password.verifying': 'Verifying...',
    'auth.forgot_password.reset_password': 'Reset Password',
    'auth.forgot_password.updating': 'Updating...',
    'auth.forgot_password.back_to_login': 'Back to Login',
    'auth.forgot_password.server_unavailable': 'Server unavailable. Check that the server is running.',
    'auth.forgot_password.connection_error': 'Cannot connect to server. Check that the server is running.',
    'auth.forgot_password.server_error': 'Server unavailable',
    'auth.forgot_password.unknown_error': 'An error occurred',
    'auth.forgot_password.passwords_no_match': 'Passwords do not match',
    // Portfolio translations
    'portfolio.our_work': 'Our Work',
    'portfolio.loading': 'Loading...',
    'portfolio.organized_portfolio': 'Discover our portfolio organized by categories',
    'portfolio.loading_projects': 'Loading projects...',
    'portfolio.no_projects': 'No projects available at the moment.',
    // Rating additional translations
    'rating.discover_feedback': 'Discover what our clients think about our services',
    'rating.checking': 'Checking...',
    'rating.login_required': 'Login Required',
    'rating.login_required_desc': 'You must be logged in to give a review on our services.',
    'rating.rating_label': 'Rating',
    'rating.comment_label': 'Comment',
    'rating.comment_placeholder': 'Share your experience...',
    'rating.characters': 'characters',
    'rating.minimum': 'minimum',
    'rating.sending': 'Sending...',
    // Contact additional translations
    'contact.logged_in_as': 'Logged in as',
    'contact.info_prefilled': 'Your information is pre-filled',
    'contact.tip': 'Tip',
    'contact.create_account_tip': 'Create an account for a faster experience!',
    'contact.logged_users_benefit': 'Logged in users don\'t need to re-enter their information.',
    'contact.add_service': 'Add Service',
    'contact.required_services': 'Required Services',
    'contact.service': 'Service',
    'contact.not_specified': 'Not specified',
    'contact.material': 'Material',
    'contact.size': 'Size',
    'contact.quantity': 'Quantity',
    'contact.edit': 'Edit',
    'contact.delete': 'Delete',
    'contact.find_us': 'Find Us',
    'contact.location': 'Industrial Zone Gzenaya, Tangier',
    'contact.edit_service': 'Edit Service',
    'contact.service_type': 'Service Type',
    'contact.select_service': 'Select a service',
    'contact.printing': 'Printing',
    'contact.cutting': 'Cutting',
    'contact.cnc': 'CNC',
    'contact.laser': 'Laser',
    'contact.size_example': 'e.g.: 100cm × 70cm',
    'contact.quantity_example': 'e.g.: 10 pieces',
    'contact.thickness': 'Thickness',
    'contact.thickness_example': 'e.g.: 3mm',
    'contact.colors': 'Colors',
    'contact.colors_example': 'Red, blue, white...',
    'contact.finishing': 'Finishing',
    'contact.finishing_example': 'Matte, glossy, laminated, mounted...',
    'contact.cancel': 'Cancel',
    'contact.add': 'Add',
    // Additional rating translations
    'rating.view_less': 'View less',
    'rating.signatech_client': 'SignaTech Client',
    'rating.client_evaluations': 'Client Evaluations',
    // Common translations
    'common.error': 'Error',
    // Auth translations
    'auth.login': 'Login',
    'auth.login_desc': 'Sign in to access the form',
    'auth.email': 'Email',
    'auth.email_placeholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot password?',
    'auth.password_placeholder': '••••••••',
    'auth.logging_in': 'Logging in...',
    'auth.login_button': 'Sign in',
    'auth.or': 'Or',
    'auth.continue_google': 'Continue with Google',
    'auth.no_account': 'Don\'t have an account?',
    'auth.create_account': 'Create account',
    // Admin page translations
    'admin.dashboard': 'Dashboard',
    'admin.images': 'Images',
    'admin.files': 'Files',
    'admin.projects': 'Projects',
    'admin.theme': 'Theme',
    'admin.contact': 'Contact',
    'admin.admins': 'Admins',
    'admin.users': 'Users',
    'admin.submissions': 'Submissions',
    'admin.panel': 'Admin Panel',
    'admin.dashboard_title': 'Admin Dashboard',
    'admin.dashboard_desc': 'Manage users and view contact submissions',
    'admin.notifications_updated': 'Notifications updated',
    'admin.notifications_enabled': 'Notifications enabled successfully',
    'admin.notifications_disabled': 'Notifications disabled successfully',
    'admin.loading_admin_data': 'Loading admin data...',
    'admin.loading_images': 'Loading images...',
    'admin.loading_projects': 'Loading projects...',
    'admin.loading_theme_settings': 'Loading theme settings...',
    'admin.loading_contact_settings': 'Loading contact settings...',
    'admin.loading_reviews': 'Loading reviews...',
    'admin.admin_management': 'Admin Management',
    'admin.create_admin': 'Create Admin',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.created': 'Created',
    'admin.company': 'Company',
    'admin.phone': 'Phone',
    'admin.role': 'Role',
    'admin.registered': 'Registered',
    'admin.view_details': 'View Details',
    'admin.delete_user': 'Delete User',
    'admin.contact_submissions': 'Contact Submissions',
    'admin.user_requests': '{name} Requests ({count} request{plural})',
    'admin.no_requests_found': 'No requests found for this user.',
    'admin.create_new_admin': 'Create New Admin',
    'admin.admin_name': 'Admin name',
    'admin.admin_email': 'admin@example.com',
    'admin.password': 'Password',
    'admin.minimum_characters': 'Minimum 6 characters',
    'admin.cancel': 'Cancel',
    'admin.create': 'Create',
    'admin.confirm_delete': 'Confirm Deletion',
    'admin.confirm_delete_user': 'Are you sure you want to delete {name}\'s account? This action is irreversible.',
    'admin.delete': 'Delete',
    'admin.admin_created': 'Admin Created',
    'admin.admin_created_success': 'New administrator has been created successfully',
    'admin.user_deleted': 'User Deleted',
    'admin.user_deleted_success': 'User has been deleted successfully',
    'admin.search_placeholder': 'Search users, submissions, or content...',
    
    'admin.access_denied': 'Access Denied',
    'admin.no_permission': 'You don\'t have permission to access this page.',
    // Contact Settings translations
    'contact_settings.company_info': 'Company Information',
    'contact_settings.company_name': 'Company Name',
    'contact_settings.company_tagline': 'Tagline/Slogan',
    'contact_settings.coordinates': 'Contact Details',
    'contact_settings.email_address': 'Email Address',
    'contact_settings.telephone': 'Phone',
    'contact_settings.whatsapp': 'WhatsApp',
    'contact_settings.address': 'Address',
    'contact_settings.address_french': 'Address (French)',
    'contact_settings.address_english': 'Address (English)',
    'contact_settings.opening_hours': 'Opening Hours',
    'contact_settings.short_hours_french': 'Short Hours (French)',
    'contact_settings.short_hours_english': 'Short Hours (English)',
    'contact_settings.detailed_hours_french': 'Detailed Hours (French)',
    'contact_settings.detailed_hours_english': 'Detailed Hours (English)',
    'contact_settings.separate_lines': 'Separate lines with | (pipe)',
    'contact_settings.saving': 'Saving...',
    'contact_settings.save': 'Save',
    'contact_settings.saved': 'Settings Saved',
    'contact_settings.saved_success': 'Contact information has been updated successfully.',
    'contact_settings.save_error': 'Unable to save settings.',
    // Image Manager translations
    'image_manager.title': 'Image Management',
    'image_manager.category': 'Category',
    'image_manager.all_categories': 'All categories',
    'image_manager.refresh': 'Refresh',
    'image_manager.add_new_image': 'Add new image',
    'image_manager.file': 'File',
    'image_manager.category_placeholder': 'logo, hero, portfolio, etc.',
    'image_manager.uploading': 'Uploading...',
    'image_manager.add': 'Add',
    'image_manager.size': 'Size',
    'image_manager.replace': 'Replace',
    'image_manager.no_images': 'No images found',
    'image_manager.access_denied': 'Access denied. You must be an administrator.',
    'image_manager.user': 'User',
    'image_manager.admin': 'Admin',
    'image_manager.yes': 'Yes',
    'image_manager.no': 'No',
    'image_manager.token': 'Token',
    'image_manager.present': 'Present',
    'image_manager.missing': 'Missing',
    'image_manager.reconnect': 'Reconnect',
    'image_manager.image_added': 'Image added successfully!',
    'image_manager.upload_error': 'Upload error',
    'image_manager.connection_error': 'Connection error during upload',
    'image_manager.delete_confirm': 'Are you sure you want to delete this image?',
    'image_manager.image_deleted': 'Image deleted successfully!',
    'image_manager.delete_error': 'Delete error',
    'image_manager.connection_delete_error': 'Connection error during deletion',
    'image_manager.image_replaced': 'Image replaced successfully!',
    'image_manager.replace_error': 'Replace error',
    'image_manager.connection_replace_error': 'Connection error during replacement',
    'image_manager.server_connection_error': 'Server connection error',
    // Organized Image Manager translations
    'organized_images.title': 'Organized Image Management',
    'organized_images.description': 'Each section corresponds to a specific use on the site. The order of images is important for display.',
    'organized_images.critical': 'Critical',
    'organized_images.important': 'Important',
    'organized_images.standard': 'Standard',
    'organized_images.critical_desc': 'Immediate display',
    'organized_images.important_desc': 'Main pages',
    'organized_images.standard_desc': 'Galleries',
    'organized_images.site_logo': 'Site Logo',
    'organized_images.homepage': 'Homepage',
    'organized_images.about_page': 'About Page',
    'organized_images.portfolio_carousel': 'Portfolio Carousel',
    'organized_images.logo_desc': 'Main logo displayed in header and used as favicon (tab icon)',
    'organized_images.homepage_desc': 'Main homepage images (hero + 2 portfolio previews)',
    'organized_images.about_desc': 'Team image used in the story section',
    'organized_images.portfolio_desc': 'Images for the carousel system organized by sections',
    'organized_images.limit_reached': 'Limit reached ({max} images max). Delete an image to add a new one.',
    'organized_images.favicon_info': 'Automatic Favicon',
    'organized_images.favicon_desc': 'This image will automatically be used as favicon (icon in browser tab).',
    'organized_images.favicon_formats': 'Recommended formats: PNG, SVG, ICO. The image will be automatically resized by the browser.',
    'organized_images.hero_info': 'This section is limited to 3 specific images for the homepage:',
    'organized_images.hero_main': 'Main image (Hero) - Displayed at the top of the homepage',
    'organized_images.hero_project1': 'Project preview 1 (Facade) - Displayed in portfolio section (1st card)',
    'organized_images.hero_project2': 'Project preview 2 (Craft) - Displayed in portfolio section (3rd card)',
    'organized_images.main_image': 'Main',
    'organized_images.main_hero': 'Main image (Hero)',
    'organized_images.project_preview1': 'Project preview 1 (Facade)',
    'organized_images.project_preview2': 'Project preview 2 (Craft)',
    'organized_images.team_image': 'Team image',
    'organized_images.no_images_section': 'No images in this section',
    'organized_images.carousel_organization': 'Carousel Organization',
    'organized_images.new_section': 'New Section',
    'organized_images.section_name_placeholder': 'Section name (e.g.: Web Projects)',
    'organized_images.display_order': 'Display Order',
    'organized_images.create': 'Create',
    'organized_images.project': 'Project',
    'organized_images.project_title': 'Project title',
    'organized_images.description_optional': 'Description (optional)',
    'organized_images.select_image': 'Select an image',
    'organized_images.no_projects_section': 'No projects in this section',
    'organized_images.delete_project_confirm': 'Delete this project?',
    'organized_images.no_sections': 'No sections created. Create your first section to organize your projects.',
    'organized_images.carousel_system_title': 'Portfolio Carousel System',
    'organized_images.carousel_system_desc': 'The portfolio now uses a carousel system organized by sections. Add your images in the "Portfolio Carousel" section above, then organize them into projects.',
    'organized_images.carousel_step1': 'Upload your images in the Portfolio Carousel section',
    'organized_images.carousel_step2': 'Create sections (e.g.: "Web Projects", "Mobile Applications")',
    'organized_images.carousel_step3': 'Add projects to each section with title, description and image',
    'organized_images.carousel_step4': 'Visitors will see a modern carousel with your organized projects',
    'organized_images.image_updated': 'Image updated successfully! Refresh the site page to see changes.',
    'organized_images.image_replaced': 'Image replaced successfully! Refresh the site page to see changes.',
    'organized_images.access_denied': 'Access denied',
    // Project Manager translations
    'project_manager.title': 'Project Management',
    'project_manager.new_section': 'New Section',
    'project_manager.section_name': 'Section name',
    'project_manager.active': 'Active',
    'project_manager.inactive': 'Inactive',
    'project_manager.projects': 'projects',
    'project_manager.new_project': 'New Project',
    'project_manager.project_title': 'Project title',
    'project_manager.description_optional': 'Description (optional)',
    'project_manager.select_existing_image': 'Select existing image',
    'project_manager.upload_new': 'Upload New',
    'project_manager.choose_existing_or_upload': 'Choose an existing image or upload a new one from your PC',
    'project_manager.display_order': 'Display order',
    'project_manager.delete_section_confirm': 'Are you sure you want to delete this section and all its projects?',
    'project_manager.delete_project_confirm': 'Are you sure you want to delete this project?',
    'project_manager.image_updated': 'Image updated successfully!',
    'project_manager.image_update_failed': 'Failed to update image',
    'project_manager.image_upload_error': 'Error uploading image. Please try again.',
    'project_manager.image_uploaded': 'Image uploaded successfully!',
    'project_manager.image_upload_failed': 'Failed to upload image',
    'project_manager.replace': 'Replace',
    'project_manager.add': 'Add',
    // Theme Settings translations
    'theme_settings.title': 'Theme Settings',
    'theme_settings.loading': 'Loading theme settings...',
    'theme_settings.color_presets': 'Color Presets',
    'theme_settings.default_purple': 'Default Purple',
    'theme_settings.ocean_blue': 'Ocean Blue',
    'theme_settings.forest_green': 'Forest Green',
    'theme_settings.sunset_orange': 'Sunset Orange',
    'theme_settings.custom_colors': 'Custom Colors',
    'theme_settings.primary_color': 'Primary Color',
    'theme_settings.accent_color': 'Accent Color',
    'theme_settings.background': 'Background',
    'theme_settings.card_background': 'Card Background',
    'theme_settings.text_color': 'Text Color',
    'theme_settings.gradient_settings': 'Gradient Settings',
    'theme_settings.gradient_start': 'Gradient Start',
    'theme_settings.gradient_end': 'Gradient End',
    'theme_settings.gradient_direction': 'Gradient Direction',
    'theme_settings.diagonal_down_right': 'Diagonal Down-Right (↘)',
    'theme_settings.top_to_bottom': 'Top to Bottom (↓)',
    'theme_settings.left_to_right': 'Left to Right (→)',
    'theme_settings.diagonal_up_right': 'Diagonal Up-Right (↗)',
    'theme_settings.right_to_left': 'Right to Left (←)',
    'theme_settings.bottom_to_top': 'Bottom to Top (↑)',
    'theme_settings.diagonal_down_left': 'Diagonal Down-Left (↙)',
    'theme_settings.diagonal_up_left': 'Diagonal Up-Left (↖)',
    'theme_settings.theme_history': 'Theme History',
    'theme_settings.theme': 'Theme',
    'theme_settings.stop_preview': 'Stop Preview',
    'theme_settings.preview': 'Preview',
    'theme_settings.apply_theme': 'Apply Theme',
    'theme_settings.saving': 'Saving...',
    'theme_settings.reset': 'Reset',
    'theme_settings.preview_mode_active': 'Preview Mode Active',
    // User Manager translations
    'user_manager.title': 'User Management',
    'user_manager.users': 'users',
    'user_manager.admin': 'Admin',
    'user_manager.client': 'Client',
    'user_manager.registered_on': 'Registered on',
    'user_manager.delete': 'Delete',
    'user_manager.your_account': 'Your account',
    'user_manager.no_users': 'No users found',
    'user_manager.delete_confirm': 'Are you sure you want to delete {name}\'s account? This action is irreversible.',
    'user_manager.user_deleted': 'User deleted successfully',
    'user_manager.delete_error': 'Error during deletion'
  }
};